import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const TRANSLATIONS = {
  EN: {
    // Top Bar & Branding
    govSupportTag: 'Govt. of India & Ministry of Cooperation Supported',
    portalSubHeader: 'Government of India • Labour Cooperative Federation Portal',
    brandName: 'Shram Setu',
    brandSubtitle: 'Cooperative Gig Services Portal',
    tollFreeLabel: 'Toll-Free Helpline',
    listenVoice: 'Listen to Page',
    stopVoice: 'Stop Voice',
    contrastBtn: 'Contrast',
    loginBtn: 'Login',
    registerBtn: 'Register',
    dashboardBtn: 'Dashboard',
    signOutBtn: 'Sign Out',

    // Live Ticker
    tickerLabel: 'Live Notice',
    tickerText: '100% ITI & Police-verified cooperative artisans across all 30 districts • Regulated base tariffs • 7-Day free repair guarantee • Toll-Free Booking: 1800-345-7788',

    // Hero Section
    heroTitlePart1: 'Verified Trade Skills.',
    heroTitlePart2: 'Fair Regulated Tariffs.',
    heroTitlePart3: 'Empowered Artisan Community.',
    heroSubtitle: 'Connect with certified, background-verified skilled professionals affiliated with regional Labour Cooperative Federations across India. Regulated tariffs, zero surge pricing, and direct social security.',
    btnBookNow: 'Book a Service',
    btnFindWorker: 'Find a Worker',
    btnJoinWorker: 'Are you a skilled artisan? Join your local Cooperative Federation →',

    // Quick Booking Console (Hero)
    quickSearchTitle: 'Quick Artisan Search & Instant Booking',
    liveDispatchActive: 'Live Dispatch Active',
    selectServiceLabel: '1. Select Service / Trade',
    selectDistrictLabel: '2. Select District',
    enterProblemLabel: '3. Describe Problem / Speak',
    searchBtn: 'Search',
    allServicesOption: '-- All 12 Services --',
    quickTagsLabel: 'Quick Tags:',

    // Floating Hero Cards
    nearbyArtisanTag: 'Live Nearby Artisan',
    fixedRateTag: 'Fixed Base Rate',
    sampleWorkerName: 'Ramesh Kumar',
    sampleWorkerRole: 'Master Electrician • ITI Gold Certified',
    sampleWorkerStats: '124+ Jobs Completed • 1.2 km away',
    policeVerifiedBadge: 'Police & Aadhaar Verified',
    bookNowShort: 'Book Now →',
    guaranteeCardTitle: '7-Day Free Workmanship Guarantee',
    guaranteeCardDesc: 'If any issue arises within 7 days, a Senior Master Artisan resolves it at ₹0 cost.',
    welfareCardTitle: '100% Artisan Social Security',
    welfareCardDesc: 'Every booking directly contributes 10% to the artisan’s ESIC healthcare & pension fund.',

    // Trust Pillars (Hero bottom)
    pillar1Title: '100% Verified Artisans',
    pillar1Desc: 'ITI / NSDC & Police background verified',
    pillar2Title: 'Zero Surge Pricing',
    pillar2Desc: 'Regulated government base tariffs',
    pillar3Title: '100% Social Security',
    pillar3Desc: 'Healthcare & pension welfare coverage',

    // Problem Matcher Section
    problemMatcherBadge: 'Instant Problem Matcher',
    problemMatcherTitle: 'What issue do you have at home? Get transparent solutions',
    tabElectrical: '⚡ Electrical',
    tabPlumbing: '🚰 Plumbing',
    tabAppliance: '❄️ Appliance / AC',
    tabCarpentry: '🔨 Carpentry / Locks',
    likelyPartsLabel: 'Standard ISI Locked Parts:',
    baseRateTag: 'Standard Labour Base Rate:',
    zeroSurgeNotice: '✓ Zero surge pricing • Official Form IV GST bill • 7-day warranty',
    bookThisServiceBtn: 'Book This Service Now',

    // Problem Items
    probElecTitle: '⚡ Electrical & Wiring Issues',
    probElecSub: 'Electrical Faults & Short Circuits',
    probElecItems: [
      'Frequent MCB tripping or sparking',
      'Inverter & UPS wiring faults',
      'Switchboard, ceiling fan & light repair',
      'Geyser & heavy load main line wiring'
    ],
    probElecParts: 'ISI Grade Copper Wire, Havells MCB, Anchor Modular Switches',

    probPlumbTitle: '🚰 Plumbing & Water Leakage',
    probPlumbSub: 'Plumbing & Pipe Line Repairs',
    probPlumbItems: [
      'Water dripping under kitchen sink & basin',
      'Overhead water tank overflow / jammed valve',
      'Motor water pump repair & new fitting',
      'Underground pipeline leakage & drain block'
    ],
    probPlumbParts: 'Astral CPVC Concealed Pipes, Brass Ball Valve, Teflon Seal',

    probAppTitle: '❄️ AC, Refrigerator & Washing Machine',
    probAppSub: 'Home Appliance Diagnostics & Gas Refill',
    probAppItems: [
      'AC not cooling / gas leakage detection',
      'Washing machine spinner or motor fault',
      'Refrigerator compressor overheating',
      'Microwave & induction cooker repair'
    ],
    probAppParts: 'Original 45uF Run Capacitor, R32 Eco Gas, PCB Relays',

    probCarpTitle: '🔨 Doors, Locks & Furniture Repairs',
    probCarpSub: 'Carpentry, Locks & Wooden Fixtures',
    probCarpItems: [
      'Main entrance lock & brass handle replacement',
      'Modular kitchen hydraulic hinge repair',
      'Wooden sofa & bed framing restoration',
      'Plywood partition & wardrobe slider repair'
    ],
    probCarpParts: 'Godrej Ultra Brass Lock, SS Heavy Duty Hinges',

    // Rural 1-Tap Action Cards
    ruralSectionBadge: 'Citizen Support Desk • Rural & Assisted Access',
    ruralSectionTitle: 'Easy & Accessible Booking for Every Citizen',
    callBookingTag: 'Direct Phone Booking',
    callBookingTitle: 'Call Toll-Free',
    callBookingDesc: 'Book an artisan directly over the phone without internet access:',
    callBookingSub: '24x7 Free Service →',
    cscBookingTag: 'Offline Kiosk Assistance',
    cscBookingTitle: 'Jan Seva Kendra (CSC)',
    cscBookingDesc: 'Book with an official receipt at your nearest Panchayat Mo Seva Kendra.',
    cscBookingSub: 'Find Nearest Kiosk →',
    guaranteeTag: 'Government Assurance',
    guaranteeTitle: '7-Day Guarantee',
    guaranteeDesc: 'Free rework by Master Artisan if any defect occurs within 7 days.',
    guaranteeSub: '100% Government Backed',
    emergencyTag: 'Immediate Priority',
    emergencyTitle: '24/7 Emergency Service',
    emergencyDesc: 'Priority dispatch within 30 minutes for short circuits or burst pipes.',
    emergencySub: 'Book Emergency Service →',

    // Categories / Services Section
    secServices: 'Standardized Public Services',
    secServicesSub: 'Transparent government-regulated base pricing with verified trade certifications',
    catElectrical: 'Electrical Repair & Wiring',
    catPlumbing: 'Plumbing & Pipe Fitting',
    catCarpentry: 'Carpentry & Furniture',
    catPainting: 'Painting & Wall Coating',
    catCleaning: 'Deep Cleaning & Sanitation',
    catGardening: 'Gardening & Landscaping',
    catCaregiving: 'Elder & Patient Caregiving',
    catDriving: 'Commercial & Personal Driving',
    catAppliance: 'AC & Appliance Repair',
    catDomestic: 'Domestic Helper & Cooking',
    catTechnician: 'CCTV & IT Technician',
    catEmergency: '24/7 Priority Emergency Services',

    descElectrical: 'Wiring, short-circuit, inverter & switchboard',
    descPlumbing: 'Pipe fitting, motor pump, leakage & drainage',
    descCarpentry: 'Furniture repair, door locks & woodwork',
    descPainting: 'Interior, exterior, putty & waterproofing',
    descCleaning: 'Home deep sanitation, kitchen & tank cleaning',
    descAppliance: 'AC servicing, refrigerator & washing machine',
    descGardening: 'Lawn trimming, plant care & landscaping',
    descCaregiving: 'Elderly care, patient bedside assistance & nurse',
    descDriving: 'Verified commercial & private transit drivers',
    descDomestic: 'Household helpers, cooks & housekeeping',
    descTechnician: 'CCTV setup, Wi-Fi networking & PC repair',
    descEmergency: 'Immediate priority dispatch within 30 mins',

    startingAt: 'Starting at',
    verifiedArtisans: 'verified artisans',
    viewArtisansBtn: 'Artisans',
    bookBtn: 'Book',
    viewAllTariffsBtn: 'View Complete Official Tariff Directory',

    // 3-Step Simple Guide
    howItWorksBadge: 'Simple & Transparent • Easy 3-Step Booking',
    howItWorksTitle: 'How to Book a Certified Artisan from Home?',
    howItWorksSub: 'Safe, government-regulated process ensuring quality work and peace of mind.',
    step1Title: 'Select Service & Problem',
    step1Desc: 'Choose service or dictate your issue by voice. Regulated base rate displays instantly.',
    step2Title: 'Schedule Time & Location',
    step2Desc: 'Pick your convenient time slot. Nearest verified cooperative artisan is assigned.',
    step3Title: 'Safe Work & Official Invoice',
    step3Desc: 'Artisan arrives with ID badge & OTP verification. Receive official Form IV GST Tax Bill.',

    // Stats Section
    welfareHeading: '100% Social Security for Every Artisan',
    welfareSub: 'Every booking directly funds healthcare, accident insurance, and pension reserves for registered cooperative workers.',
    statVerifiedWorkers: 'Verified Artisans',
    statCooperatives: 'Active Federations',
    statJobsCompleted: 'Jobs Fulfilled',
    statSatisfaction: 'Satisfaction Rate',

    // Worker Onboarding Banner
    workerCampaignBadge: '👷 Skilled Artisan Registration Campaign',
    workerCampaignTitle: 'Are you a skilled artisan? Join today!',
    workerCampaignDesc: 'Affiliate with your regional Labour Cooperative Federation to receive 0% commission deductions, 100% ESIC health cover, accident insurance, pension corpus, and dignified daily earnings.',
    workerJoinBtn: 'Register as Artisan →',

    // Navigation Links
    navHome: 'Home',
    navServices: 'Services',
    navFindWorker: 'Find Worker',
    navBookService: 'Book Service',
    navAbout: 'About',
    navHelp: 'Help',

    // Common Buttons
    btnCancel: 'Cancel',
    btnPrintBill: 'Print Form IV Bill',
    btnViewTimeline: 'View Timeline & Details',
    btnPay: 'Pay Now',
    btnSubmit: 'Submit',

    // FindWorker Page
    findWorkerBadge: 'Certified Cooperative Worker Directory',
    findWorkerTitle: 'Find Verified Cooperative Workers',
    findWorkerSub: 'Browse certified professionals affiliated with registered Labour Cooperative Federations across all districts.',
    voiceSearchTitle: 'Speak to Search',
    tradeLabel: 'Trade',
    districtLabel: 'District',
    statusLabel: 'Status',
    allTrades: 'All Trades',
    allDistricts: 'All Districts',
    anyStatus: 'Any Status',
    statusAvailable: 'Available Now',
    statusBusy: 'Engaged',
    statusOffline: 'Offline',
    verifiedOnly: 'Verified Only',
    resetFilters: 'Reset all filters',
    verified: 'Verified',
    pending: 'Pending',
    viewProfile: 'View Profile',
    noWorkersFound: 'No workers matched your search filters.',
    loadingWorkers: 'Loading verified cooperative workers...',
    bookThisArtisan: 'Book This Artisan',
    coopAffiliation: 'Cooperative Affiliation',
    primaryTrade: 'Primary Trade',
    experience: 'Experience',
    rating: 'Rating',
    completed: 'Completed',
    years: 'Years',
    artisanBio: 'Artisan Bio',
    close: 'Close',

    // Services Page
    servicesDirectoryBadge: 'Standardized Government Service Tariff Directory',
    zeroSurgeBannerTitle: 'Zero Surge Pricing Guarantee',
    zeroSurgeBannerDesc: 'All prices are standardized by the State Cooperative Federation. No algorithmic peak pricing or hidden fees.',
    tollFreeBookingLabel: 'Toll-Free Phone Booking',
    searchServicesPlaceholder: 'Search services by keyword (e.g., electrical repair, leakage, deep clean)...',
    categoryLabel: 'Category',
    allCategories: 'All Services',
    clearFilters: 'Clear filters & search',
    loadingServices: 'Loading cooperative services directory...',
    noServicesFound: 'No services found matching your criteria.',
    viewWorkers: 'View workers',
    verifiedWorkerCount: 'verified workers',
    coopBaseRate: 'Coop Base Rate',
    priorityEmergency: '24/7 Priority Emergency Service',
    responseTime: '30 Min Response',

    // CustomerBookings Page
    myBookingsTitle: 'My Service Bookings',
    myBookingsSub: 'Track and manage your home service orders',
    bookNewService: 'Book New Service',
    tabAll: 'All',
    tabActive: 'Active',
    tabCompleted: 'Completed',
    tabCancelled: 'Cancelled',
    statusRequested: 'Requested',
    statusMatched: 'Worker Assigned',
    statusAccepted: 'Accepted',
    statusInProgress: 'In Progress',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    confirmCancel: 'Are you sure you want to cancel this booking?',
    noBookings: 'No bookings found.',
    bookFirstService: 'Book your first service to get started.',
    warrantyBadge: '7-Day Free Workmanship Guarantee',
    warrantySub: 'If any issue arises within 7 days, a Senior Master Artisan resolves it at zero cost.',

    // Trade Categories
    catElectrical: 'Electrical',
    catPlumbing: 'Plumbing',
    catCarpentry: 'Carpentry',
    catPainting: 'Painting',
    catCleaning: 'Cleaning',
    catGardening: 'Gardening',
    catCaregiving: 'Caregiving',
    catDriving: 'Driving',
    catAppliance: 'Appliance Repair',
    catDomestic: 'Domestic Help',
    catTechnician: 'IT / Technician',

    // Misc
    searchBtn: 'Search',
    resetAllFilters: 'Reset all filters',

    // Problem Search & Booking (BookService)
    problemSearchTitle: 'Problem Search & Tariff Matcher',
    problemSearchSub: 'Describe your repair issue or select a common problem',
    problemSearchDesc: 'Our system instantly matches your repair requirement with certified cooperative trade rates and standard ISI parts.',
    searchIssuePlaceholder: 'Type your issue (e.g. leaking tap, fan not working, AC gas, switch sparking)...',
    btnFindServiceRate: 'Find Service & Tariff',
    matchedService: 'Matched Service',
    govStandardRate: 'Govt. Regulated Tariff',
    orSelectManual: 'Or Select from All Standardized Public Services',
    matchingServicesFound: 'Matching Services Found',
    clearSearch: 'Clear Search',
    btnContinueQuote: 'Continue with Selected Service',
  },

  HI: {
    // Top Bar & Branding
    govSupportTag: 'भारत सरकार एवं सहकारिता मंत्रालय समर्थित',
    portalSubHeader: 'भारत सरकार • श्रम सहकारी महासंघ पोर्टल',
    brandName: 'श्रम सेतु',
    brandSubtitle: 'सहकारी गिग सेवा पोर्टल',
    tollFreeLabel: 'टोल-फ्री हेल्पलाइन',
    listenVoice: 'बोलकर सुनें',
    stopVoice: 'रुकें',
    contrastBtn: 'कंट्रास्ट',
    loginBtn: 'लॉगिन',
    registerBtn: 'पंजीकरण',
    dashboardBtn: 'डैशबोर्ड',
    signOutBtn: 'लॉगआउट',

    // Live Ticker
    tickerLabel: 'लाइव सूचना',
    tickerText: 'सभी 30 जिलों में 100% आईटीआई एवं पुलिस-सत्यापित सहकारी कारीगर उपलब्ध • सरकारी नियंत्रित दरें • 7-दिवसीय निःशुल्क मरम्मत वारंटी • टोल-फ्री बुकिंग: 1800-345-7788',

    // Hero Section
    heroTitlePart1: 'सत्यापित ट्रेड कौशल।',
    heroTitlePart2: 'उचित सरकारी दरें।',
    heroTitlePart3: 'सशक्त श्रमिक समुदाय।',
    heroSubtitle: 'ओडिशा भर के क्षेत्रीय श्रम सहकारी संघों से जुड़े प्रमाणित, पृष्ठभूमि-सत्यापित कुशल पेशेवरों से जुड़ें। सरकारी दरें, शून्य अतिरिक्त शुल्क और सामाजिक सुरक्षा।',
    btnBookNow: 'सेवा बुक करें',
    btnFindWorker: 'कारीगर खोजें',
    btnJoinWorker: 'क्या आप एक कुशल श्रमिक हैं? अपने स्थानीय सहकारी संघ से जुड़ें →',

    // Quick Booking Console (Hero)
    quickSearchTitle: 'त्वरित कारीगर खोज एवं बुकिंग',
    liveDispatchActive: 'लाइव आवंटन सक्रिय',
    selectServiceLabel: '1. ट्रेड या सेवा चुनें',
    selectDistrictLabel: '2. जिला चुनें',
    enterProblemLabel: '3. समस्या लिखें या बोलें',
    searchBtn: 'खोजें',
    allServicesOption: '-- सभी 12 सेवाएँ --',
    quickTagsLabel: 'त्वरित:',

    // Floating Hero Cards
    nearbyArtisanTag: 'निकटतम सत्यापित कारीगर',
    fixedRateTag: 'फिक्स्ड आधार दर',
    sampleWorkerName: 'रमेश कुमार',
    sampleWorkerRole: 'मास्टर इलेक्ट्रीशियन • ITI Gold Certified',
    sampleWorkerStats: '124+ कार्य पूर्ण • 1.2 km दूर',
    policeVerifiedBadge: 'पुलिस एवं आधार सत्यापित',
    bookNowShort: 'तुरंत बुक करें →',
    guaranteeCardTitle: '7-दिवसीय सरकारी मरम्मत वारंटी',
    guaranteeCardDesc: 'कार्य में असंतुष्टि पर 7 दिन में मास्टर कारीगर द्वारा ₹0 में निःशुल्क सुधार।',
    welfareCardTitle: '100% कारीगर सामाजिक सुरक्षा',
    welfareCardDesc: 'प्रत्येक बुकिंग से सीधा 10% अंशदान श्रमिक के ESIC स्वास्थ्य व पेंशन खाते में।',

    // Trust Pillars (Hero bottom)
    pillar1Title: '100% प्रमाणित कारीगर',
    pillar1Desc: 'ITI / NSDC एवं पुलिस सत्यापित',
    pillar2Title: 'शून्य अतिरिक्त शुल्क',
    pillar2Desc: 'सरकारी विनियमित आधार दरें',
    pillar3Title: '100% सामाजिक सुरक्षा',
    pillar3Desc: 'श्रमिक स्वास्थ्य व पेंशन कवर',

    // Problem Matcher Section
    problemMatcherBadge: 'स्मार्ट समस्या निदान',
    problemMatcherTitle: 'घर में क्या समस्या है? तुरंत पारदर्शी समाधान पाएं',
    tabElectrical: '⚡ बिजली',
    tabPlumbing: '🚰 प्लंबर',
    tabAppliance: '❄️ एसी / फ्रिज',
    tabCarpentry: '🔨 बढ़ई / ताला',
    likelyPartsLabel: 'संभावित मानक सामग्री:',
    baseRateTag: 'मानक श्रम आधार दर:',
    zeroSurgeNotice: '✓ शून्य सर्च मूल्य • फॉर्म IV पक्का टैक्स बिल • 7-दिन वारंटी',
    bookThisServiceBtn: 'यह सेवा तुरंत बुक करें',

    // Problem Items
    probElecTitle: '⚡ बिजली एवं वायरिंग संबंधी समस्याएँ',
    probElecSub: 'विद्युत फॉल्ट एवं शॉर्ट सर्किट',
    probElecItems: [
      'MCB बार-बार ट्रिप होना या स्पार्किंग',
      'इनवर्टर व यूपीएस वायरिंग फॉल्ट',
      'स्विचबोर्ड, पंखा व ट्यूबलाइट रिपेयर',
      'गीजर व हैवी लोड मेन लाइन वायरिंग'
    ],
    probElecParts: 'ISI मार्का कॉपर वायर, हैवेल्स MCB, एंकर स्विच',

    probPlumbTitle: '🚰 नलसाजी व पानी लीकेज समस्याएँ',
    probPlumbSub: 'पाइपलाइन व सेनेटरी कार्य',
    probPlumbItems: [
      'किचन सिंक व बेसिन के नीचे पानी टपकना',
      'ओवरहेड वॉटर टैंक ओवरफ्लो / वाल्व जाम',
      'मोटर पंप मोटर मरम्मत व नया फिटिंग',
      'अंडरग्राउंड पाइपलाइन लीकेज व ड्रेनेज ब्लॉकेज'
    ],
    probPlumbParts: 'एस्ट्रल CPVC पाइप, ब्रास बॉल वाल्व, टेफ्लॉन टेप',

    probAppTitle: '❄️ एसी, फ्रिज एवं वाशिंग मशीन',
    probAppSub: 'उपकरण जांच एवं गैस रिफिल',
    probAppItems: [
      'एसी कूलिंग न करना / गैस लीकेज जांच',
      'वाशिंग मशीन ड्रायर या स्पिनर मोटर फॉल्ट',
      'फ्रिज कंप्रेसर गर्म होना व कूलिंग बंद',
      'माइक्रोवेव व इंडक्शन चूल्हा मरम्मत'
    ],
    probAppParts: 'ओरिजिनल 45uF कैपेसिटर, R32 गैस, PCB रिले',

    probCarpTitle: '🔨 दरवाजे, ताले एवं फर्नीचर सुधार',
    probCarpSub: 'बढ़ईगीरी व लकड़ी कार्य',
    probCarpItems: [
      'मुख्य दरवाजा लॉक व हैंडल बदलना',
      'मॉड्यूलर किचन हाइड्रोलिक हिंज रिपेयर',
      'सोफा व बेड की लकड़ी मरम्मत',
      'प्लाईवुड पार्टीशन व वार्डरोब स्लाइडर'
    ],
    probCarpParts: 'गोदरेज ब्रास लॉक, स्टेनलेस स्टील कब्जे',

    // Rural 1-Tap Action Cards
    ruralSectionBadge: 'नागरिक सहायता केंद्र • ग्रामीण एवं वरिष्ठ नागरिक सुविधा',
    ruralSectionTitle: 'सभी नागरिकों के लिए आसान व सुगम बुकिंग व्यवस्था',
    callBookingTag: 'फोन पर सीधी बुकिंग',
    callBookingTitle: 'टोल-फ्री कॉल करें',
    callBookingDesc: 'बिना इंटरनेट के सीधे फोन से कारीगर बुक करने के लिए डायल करें:',
    callBookingSub: '24x7 निःशुल्क सेवा →',
    cscBookingTag: 'ऑफ़लाइन सेवा सहायता',
    cscBookingTitle: 'जन सेवा केंद्र (CSC)',
    cscBookingDesc: 'अपने नजदीकी पंचायत मो सेवा केंद्र (CSC) से रसीद सहित बुकिंग कराएं।',
    cscBookingSub: 'नजदीकी केंद्र देखें →',
    guaranteeTag: 'सरकारी आश्वासन',
    guaranteeTitle: '7-दिवसीय वारंटी',
    guaranteeDesc: 'कार्य में कोई कमी आने पर 7 दिनों के भीतर वरिष्ठ मास्टर कारीगर द्वारा ₹0 में सुधार।',
    guaranteeSub: '100% सरकारी गारंटी',
    emergencyTag: 'तत्काल प्राथमिकता',
    emergencyTitle: '24/7 आपातकालीन सेवा',
    emergencyDesc: 'शॉर्ट-सर्किट या मुख्य पाइप फटने पर 30 मिनट में प्राथमिकता आवंटन।',
    emergencySub: 'आपातकालीन बुकिंग →',

    // Categories / Services Section
    secServices: 'मानकीकृत सार्वजनिक सेवाएँ',
    secServicesSub: 'सत्यापित व्यापार प्रमाणपत्रों के साथ पारदर्शी सरकारी-विनियमित आधार मूल्य निर्धारण',
    catElectrical: 'विद्युत मरम्मत एवं वायरिंग',
    catPlumbing: 'नलसाजी (प्लंबर) कार्य',
    catCarpentry: 'बढ़ईगीरी एवं फर्नीचर',
    catPainting: 'पेंटिंग एवं दीवार कोटिंग',
    catCleaning: 'गहन सफाई एवं स्वच्छता',
    catGardening: 'बागवानी एवं भू-निर्माण',
    catCaregiving: 'बुजुर्ग एवं रोगी देखभाल',
    catDriving: 'वाहन चालक (ड्राइवर)',
    catAppliance: 'एसी एवं उपकरण मरम्मत',
    catDomestic: 'घरेलू सहायता एवं रसोइया',
    catTechnician: 'सीसीटीवी एवं आईटी तकनीशियन',
    catEmergency: '24/7 आपातकालीन सेवाएँ',

    descElectrical: 'वायरिंग, शॉर्ट-सर्किट, इन्वर्टर एवं स्विचबोर्ड',
    descPlumbing: 'पाइप फिटिंग, मोटर पंप, रिसाव एवं जल निकासी',
    descCarpentry: 'फर्नीचर मरम्मत, दरवाज़े के ताले एवं लकड़ी का काम',
    descPainting: 'आंतरिक, बाहरी, पुट्टी एवं वॉटरप्रूफिंग',
    descCleaning: 'घर की गहरी सफाई, रसोई एवं पानी टंकी सफाई',
    descAppliance: 'एसी सर्विसिंग, फ्रिज एवं वाशिंग मशीन',
    descGardening: 'लॉन कटाई, पौधों की देखभाल एवं बागवानी',
    descCaregiving: 'बुजुर्गों की देखभाल, रोगी सहायता एवं नर्स',
    descDriving: 'सत्यापित वाणिज्यिक और निजी ड्राइवर',
    descDomestic: 'घरेलू सहायक, रसोइये एवं हाउसकीपिंग',
    descTechnician: 'सीसीटीवी सेटअप, वाई-फाई और पीसी मरम्मत',
    descEmergency: '30 मिनट के भीतर तत्काल प्राथमिकता सेवा',

    startingAt: 'प्रारंभिक मूल्य',
    verifiedArtisans: 'सत्यापित कारीगर',
    viewArtisansBtn: 'कारीगर',
    bookBtn: 'बुक करें',
    viewAllTariffsBtn: 'सभी 12 ट्रेड की सरकारी दर सूची देखें',

    // 3-Step Simple Guide
    howItWorksBadge: 'सरल व सुरक्षित प्रक्रिया • आसान 3-चरणीय बुकिंग',
    howItWorksTitle: 'घर बैठे सरकारी प्रमाणित कारीगर कैसे बुलाएं?',
    howItWorksSub: 'बिना किसी परेशानी के पारदर्शी सरकारी प्रक्रिया द्वारा सुरक्षित कार्य संपन्न कराएं।',
    step1Title: 'समस्या व सेवा चुनें',
    step1Desc: 'वेबसाइट पर सेवा चुनें या बोलकर अपनी समस्या बताएं। तय सरकारी आधार मूल्य तुरंत दिखेगा।',
    step2Title: 'समय व पता निश्चित करें',
    step2Desc: 'अपनी सुविधानुसार समय चुनें। निकटतम सहकारी महासंघ द्वारा सत्यापित कारीगर आवंटित होगा।',
    step3Title: 'सुरक्षित कार्य व सरकारी बिल',
    step3Desc: 'कारीगर पहचान पत्र एवं ओटीपी सत्यापन के साथ पहुंचेगा। कार्य पूर्ण होने पर फॉर्म IV बिल प्राप्त करें।',

    // Stats Section
    welfareHeading: 'प्रत्येक कारीगर के लिए 100% सामाजिक सुरक्षा',
    welfareSub: 'प्रत्येक बुकिंग सीधे पंजीकृत सहकारी श्रमिकों के स्वास्थ्य बीमा, दुर्घटना कवर और पेंशन का समर्थन करती है।',
    statVerifiedWorkers: 'सत्यापित कारीगर',
    statCooperatives: 'सक्रिय महासंघ',
    statJobsCompleted: 'पूर्ण किए गए कार्य',
    statSatisfaction: 'संतुष्टि दर',

    // Worker Onboarding Banner
    workerCampaignBadge: '👷 कुशल कारीगर पंजीकरण महा-अभियान',
    workerCampaignTitle: 'क्या आप एक कुशल कारीगर हैं? आज ही जुड़ें!',
    workerCampaignDesc: 'अपने स्थानीय श्रम सहकारी महासंघ से जुड़ें और पाएं शून्य कमीशन, 100% स्वास्थ्य बीमा, दुर्घटना कवर, पेंशन कोष और सम्मानजनक दैनिक आय।',
    workerJoinBtn: 'कारीगर पंजीकरण करें →',

    // Navigation Links
    navHome: 'होम',
    navServices: 'सेवाएं',
    navFindWorker: 'कारीगर खोजें',
    navBookService: 'सेवा बुक करें',
    navAbout: 'हमारे बारे में',
    navHelp: 'सहायता',

    // Common Buttons
    btnCancel: 'रद्द करें',
    btnPrintBill: 'फॉर्म IV बिल प्रिंट करें',
    btnViewTimeline: 'कार्य प्रगति देखें',
    btnPay: 'भुगतान करें',
    btnSubmit: 'जमा करें',

    findWorkerBadge: 'प्रमाणित सहकारी कारीगर निर्देशिका',
    findWorkerTitle: 'सत्यापित सहकारी कारीगर खोजें',
    findWorkerSub: 'सभी जिलों में पंजीकृत श्रम सहकारी संघों से जुड़े प्रमाणित पेशेवरों को खोजें।',
    voiceSearchTitle: 'बोलकर खोजें',
    tradeLabel: 'ट्रेड / व्यवसाय',
    districtLabel: 'जिला',
    statusLabel: 'स्थिति',
    allTrades: 'सभी ट्रेड',
    allDistricts: 'सभी जिले',
    anyStatus: 'कोई भी स्थिति',
    statusAvailable: 'उपलब्ध',
    statusBusy: 'कार्यरत',
    statusOffline: 'ऑफलाइन',
    verifiedOnly: 'केवल सत्यापित',
    resetFilters: 'सभी फ़िल्टर रीसेट करें',
    verified: 'सत्यापित',
    pending: 'लंबित',
    viewProfile: 'विवरण देखें',
    noWorkersFound: 'आपकी खोज से कोई कारीगर नहीं मिला।',
    loadingWorkers: 'सत्यापित सहकारी कारीगर लोड हो रहे हैं...',
    bookThisArtisan: 'इस कारीगर को बुक करें',
    coopAffiliation: 'सहकारी संबद्धता',
    primaryTrade: 'प्राथमिक व्यवसाय',
    experience: 'अनुभव',
    rating: 'रेटिंग',
    completed: 'पूर्ण',
    years: 'वर्ष',
    artisanBio: 'कारीगर परिचय',
    close: 'बंद करें',

    servicesDirectoryBadge: 'मानकीकृत सरकारी सेवा दर सूची',
    zeroSurgeBannerTitle: 'शून्य अतिरिक्त शुल्क गारंटी',
    zeroSurgeBannerDesc: 'सभी मूल्य राज्य सहकारी संघ द्वारा मानकीकृत हैं। कोई छिपा शुल्क नहीं।',
    tollFreeBookingLabel: 'टोल-फ्री फोन बुकिंग',
    searchServicesPlaceholder: 'सेवा खोजें (जैसे, बिजली मरम्मत, लीकेज, सफाई)...',
    categoryLabel: 'श्रेणी',
    allCategories: 'सभी सेवाएँ',
    clearFilters: 'फ़िल्टर साफ करें',
    loadingServices: 'सहकारी सेवा सूची लोड हो रही है...',
    noServicesFound: 'आपकी खोज से कोई सेवा नहीं मिली।',
    viewWorkers: 'कारीगर देखें',
    verifiedWorkerCount: 'सत्यापित कारीगर',
    coopBaseRate: 'सहकारी आधार दर',
    priorityEmergency: '24/7 प्राथमिकता आपातकालीन सेवा',
    responseTime: '30 मिनट प्रतिक्रिया',

    myBookingsTitle: 'मेरी सेवा बुकिंग्स',
    myBookingsSub: 'अपने घरेलू सेवा ऑर्डर ट्रैक और प्रबंधित करें',
    bookNewService: 'नई सेवा बुक करें',
    tabAll: 'सभी',
    tabActive: 'सक्रिय',
    tabCompleted: 'पूर्ण',
    tabCancelled: 'रद्द',
    statusRequested: 'आदेश प्राप्त',
    statusMatched: 'कारीगर आवंटित',
    statusAccepted: 'स्वीकृत',
    statusInProgress: 'कार्य प्रगति पर',
    statusCompleted: 'सफलतापूर्वक पूर्ण',
    statusCancelled: 'रद्द',
    confirmCancel: 'क्या आप वाकई यह बुकिंग रद्द करना चाहते हैं?',
    noBookings: 'कोई बुकिंग नहीं मिली।',
    bookFirstService: 'शुरू करने के लिए अपनी पहली सेवा बुक करें।',
    warrantyBadge: '7-दिवसीय निःशुल्क मरम्मत गारंटी',
    warrantySub: 'कार्य में कोई कमी आने पर 7 दिनों में वरिष्ठ मास्टर कारीगर द्वारा ₹0 में सुधार।',

    catElectrical: 'विद्युत',
    catPlumbing: 'नलसाजी',
    catCarpentry: 'बढ़ई',
    catPainting: 'पेंटिंग',
    catCleaning: 'सफाई',
    catGardening: 'बागवानी',
    catCaregiving: 'देखभाल',
    catDriving: 'चालक',
    catAppliance: 'उपकरण मरम्मत',
    catDomestic: 'घरेलू सेवा',
    catTechnician: 'IT / तकनीशियन',
    searchBtn: 'खोजें',
    resetAllFilters: 'सभी फ़िल्टर रीसेट करें',

    problemSearchTitle: 'समस्या खोज एवं सरकारी दर सूची',
    problemSearchSub: 'अपनी मरम्मत समस्या लिखें या नीचे दिए गए विकल्पों में से चुनें',
    problemSearchDesc: 'हमारा पोर्टल आपकी आवश्यकता को तुरंत प्रमाणित सरकारी दर एवं मानक सामग्री से जोड़ता है।',
    searchIssuePlaceholder: 'समस्या लिखें (जैसे नल से पानी टपकना, पंखा खराब, एसी गैस, स्विच स्पार्किंग)...',
    btnFindServiceRate: 'सेवा व दर खोजें',
    matchedService: 'संबंधित सेवा',
    govStandardRate: 'सरकारी विनियमित दर',
    orSelectManual: 'या सभी मानकीकृत सार्वजनिक सेवाओं में से चुनें',
    matchingServicesFound: 'संबंधित सेवाएँ मिलीं',
    clearSearch: 'खोज साफ करें',
    btnContinueQuote: 'चयनित सेवा के साथ आगे बढ़ें',
  },

  OR: {
    // Top Bar & Branding
    govSupportTag: 'ଭାରତ ସରକାର ଓ ସମବାୟ ମନ୍ତ୍ରଣାଳୟ ଦ୍ୱାରା ସମର୍ଥିତ',
    portalSubHeader: 'ଭାରତ ସରକାର • ଶ୍ରମ ସମବାୟ ମହାସଂଘ ପୋର୍ଟାଲ',
    brandName: 'ଶ୍ରମ ସେତୁ',
    brandSubtitle: 'ସମବାୟ ଗିଗ୍ ସେବା ପୋର୍ଟାଲ',
    tollFreeLabel: 'ଟୋଲ୍-ଫ୍ରି ହେଲ୍ପଲାଇନ୍',
    listenVoice: 'ଶୁଣନ୍ତୁ',
    stopVoice: 'ରୁହନ୍ତୁ',
    contrastBtn: 'କଣ୍ଟ୍ରାଷ୍ଟ',
    loginBtn: 'ଲଗ୍ଇନ୍',
    registerBtn: 'ପଞ୍ଜୀକରଣ',
    dashboardBtn: 'ଡ୍ୟାସବୋର୍ଡ',
    signOutBtn: 'ସାଇନ୍ ଆଉଟ୍',

    // Live Ticker
    tickerLabel: 'ସଦ୍ୟ ସୂଚନା',
    tickerText: 'ସମସ୍ତ ୩୦ ଜିଲ୍ଲାରେ ୧୦୦% ଆଇଟିଆଇ ଓ ପୋଲିସ ଯାଞ୍ଚ ହୋଇଥିବା ଶ୍ରମିକ ଉପଲବ୍ଧ • ସରକାରୀ ଦର • ୭-ଦିନିଆ ମାଗଣା ମରାମତି ଗ୍ୟାରେଣ୍ଟି • ଟୋଲ୍-ଫ୍ରି: ୧୮୦୦-୩୪୫-୭୭୮୮',

    // Hero Section
    heroTitlePart1: 'ଯାଞ୍ଚ ହୋଇଥିବା ଦକ୍ଷତା।',
    heroTitlePart2: 'ନ୍ୟାଯ୍ୟ ସରକାରୀ ଦର।',
    heroTitlePart3: 'ସଶକ୍ତ ଶ୍ରମିକ ସମାଜ।',
    heroSubtitle: 'ଓଡ଼ିଶାର ଆଞ୍ଚଳିକ ଶ୍ରମ ସମବାୟ ମହାସଂଘ ସହିତ ଜଡ଼ିତ ପ୍ରମାଣିତ ତଥା ପୃଷ୍ଠଭୂମି-ଯାଞ୍ଚ ହୋଇଥିବା କୁଶଳୀ ଶ୍ରମିକମାନଙ୍କ ସହିତ ସଂଯୋଗ କରନ୍ତୁ। ନିୟନ୍ତ୍ରିତ ଦର, କୌଣସି ଅତିରିକ୍ତ ଶୁଳ୍କ ନାହିଁ ଏବଂ ସାମାଜିକ ସୁରକ୍ଷା।',
    btnBookNow: 'ସେବା ବୁକ୍ କରନ୍ତୁ',
    btnFindWorker: 'ଶ୍ରମିକ ଖୋଜନ୍ତୁ',
    btnJoinWorker: 'ଆପଣ ଜଣେ କୁଶଳୀ ଶ୍ରମିକ କି? ନିଜ ସ୍ଥାନୀୟ ସମବାୟ ସମିତିରେ ଯୋଗ ଦିଅନ୍ତୁ →',

    // Quick Booking Console (Hero)
    quickSearchTitle: 'ଶ୍ରମିକ ସନ୍ଧାନ ଓ ତୁରନ୍ତ ବୁକିଂ',
    liveDispatchActive: 'ଲାଇଭ୍ ବଣ୍ଟନ ସକ୍ରିୟ',
    selectServiceLabel: '୧. ସେବା ଚୟନ କରନ୍ତୁ',
    selectDistrictLabel: '୨. ଜିଲ୍ଲା ଚୟନ କରନ୍ତୁ',
    enterProblemLabel: '୩. ସମସ୍ୟା ଲେଖନ୍ତୁ ବା କୁହନ୍ତୁ',
    searchBtn: 'ଖୋଜନ୍ତୁ',
    allServicesOption: '-- ସମସ୍ତ ୧୨ ସେବା --',
    quickTagsLabel: 'ତୁରନ୍ତ:',

    // Floating Hero Cards
    nearbyArtisanTag: 'ନିକଟତମ ପ୍ରମାଣିତ ଶ୍ରମିକ',
    fixedRateTag: 'ସ୍ଥିର ମୂଳ ଦର',
    sampleWorkerName: 'ରମେଶ କୁମାର',
    sampleWorkerRole: 'ମାଷ୍ଟର ଇଲେକ୍ଟ୍ରିସିଆନ୍ • ITI Gold Certified',
    sampleWorkerStats: '୧୨୪+ କାର୍ଯ୍ୟ ସମ୍ପନ୍ନ • ୧.୨ କିମି ଦୂର',
    policeVerifiedBadge: 'ପୋଲିସ ଓ ଆଧାର ଯାଞ୍ଚ ହୋଇଥିବା',
    bookNowShort: 'ତୁରନ୍ତ ବୁକ୍ କରନ୍ତୁ →',
    guaranteeCardTitle: '୭-ଦିନିଆ ସରକାରୀ ମରାମତି ଗ୍ୟାରେଣ୍ଟି',
    guaranteeCardDesc: 'କାର୍ଯ୍ୟରେ ଅସନ୍ତୋଷ ହେଲେ ୭ ଦିନ ମଧ୍ୟରେ ମାଷ୍ଟର ଶ୍ରମିକଙ୍କ ଦ୍ୱାରା ₹୦ ମୂଲ୍ୟରେ ମାଗଣା ସଂଶୋଧନ।',
    welfareCardTitle: '୧୦୦% ଶ୍ରମିକ ସାମାଜିକ ସୁରକ୍ଷା',
    welfareCardDesc: 'ପ୍ରତ୍ୟେକ ବୁକିଂରୁ ସିଧାସଳଖ ୧୦% ଅଂଶଦାନ ଶ୍ରମିକଙ୍କ ଇଏସଆଇସି ସ୍ୱାସ୍ଥ୍ୟ ଓ ପେନସନ ପାଣ୍ଠିକୁ ଯାଏ।',

    // Trust Pillars (Hero bottom)
    pillar1Title: '୧୦୦% ପ୍ରମାଣିତ ଶ୍ରମିକ',
    pillar1Desc: 'ITI / NSDC ଓ ପୋଲିସ ଯାଞ୍ଚ ହୋଇଥିବା',
    pillar2Title: 'କୌଣସି ଅତିରିକ୍ତ ଶୁଳ୍କ ନାହିଁ',
    pillar2Desc: 'ସରକାରୀ ନିୟନ୍ତ୍ରିତ ମୂଳ ଦର',
    pillar3Title: '୧୦୦% ସାମାଜିକ ସୁରକ୍ଷା',
    pillar3Desc: 'ଶ୍ରମିକ ସ୍ୱାସ୍ଥ୍ୟ ଓ ପେନସନ ବୀମା',

    // Problem Matcher Section
    problemMatcherBadge: 'ସ୍ମାର୍ଟ ସମସ୍ୟା ନିରାକରଣ',
    problemMatcherTitle: 'ଘରେ କ\'ଣ ସମସ୍ୟା ଅଛି? ତୁରନ୍ତ ସମାଧାନ ପାଆନ୍ତୁ',
    tabElectrical: '⚡ ବିଦ୍ୟୁତ୍',
    tabPlumbing: '🚰 ପ୍ଲମ୍ବିଂ',
    tabAppliance: '❄️ ଏସି / ଫ୍ରିଜ୍',
    tabCarpentry: '🔨 କାଠ କାମ / ତାଲା',
    likelyPartsLabel: 'ସମ୍ଭାବ୍ୟ ମାନକ ସାମଗ୍ରୀ:',
    baseRateTag: 'ମାନକ ଶ୍ରମ ମୂଳ ଦର:',
    zeroSurgeNotice: '✓ କୌଣସି ଅଧିକ ଦର ନାହିଁ • ଫର୍ମ IV ପକ୍କା ବିଲ୍ • ୭-ଦିନିଆ ୱାରେଣ୍ଟି',
    bookThisServiceBtn: 'ଏହି ସେବା ତୁରନ୍ତ ବୁକ୍ କରନ୍ତୁ',

    // Problem Items
    probElecTitle: '⚡ ବିଦ୍ୟୁତ୍ ଓ ୱେୟାରିଂ ସମସ୍ୟା',
    probElecSub: 'ବିଦ୍ୟୁତ୍ ତ୍ରୁଟି ଓ ସର୍ଟ ସର୍କିଟ୍',
    probElecItems: [
      'MCB ବାରମ୍ବାର ପଡ଼ିଯିବା ବା ସ୍ପାର୍କିଂ',
      'ଇନଭର୍ଟର ଓ ୟୁପିଏସ୍ ତ୍ରୁଟି',
      'ସ୍ୱିଚବୋର୍ଡ, ଫ୍ୟାନ୍ ଓ ଲାଇଟ୍ ମରାମତି',
      'ଗିଜର ଓ ମୁଖ୍ୟ ଲାଇନ୍ ୱେୟାରିଂ'
    ],
    probElecParts: 'ISI ମାର୍କା ତାର, ହାଭେଲ୍ସ MCB, ଆଙ୍କର ସୁଇଚ୍',

    probPlumbTitle: '🚰 ପ୍ଲମ୍ବିଂ ଓ ପାଣି ଲିକେଜ୍ ସମସ୍ୟା',
    probPlumbSub: 'ପାଇପଲାଇନ୍ ଓ ସାନିଟାରୀ କାର୍ଯ୍ୟ',
    probPlumbItems: [
      'ସିଙ୍କ୍ ଓ ବେସିନ୍ ତଳୁ ପାଣି ଗଳିବା',
      'ପାଣି ଟାଙ୍କି ଓଭରଫ୍ଲୋ / ଭଲ୍ଭ ଜାମ୍',
      'ମୋଟର ପମ୍ପ ମରାମତି ଓ ନୂଆ ଫିଟିଂ',
      'ଭୂତଳ ପାଇପଲାଇନ୍ ଲିକେଜ୍ ଓ ଡ୍ରେନେଜ୍ ସଫା'
    ],
    probPlumbParts: 'ଆଷ୍ଟ୍ରାଲ୍ CPVC ପାଇପ୍, ବ୍ରାସ୍ ବଲ୍ ଭଲ୍ଭ',

    probAppTitle: '❄️ ଏସି, ଫ୍ରିଜ୍ ଓ ୱାସିଂ ମେସିନ୍',
    probAppSub: 'ଉପକରଣ ଯାଞ୍ଚ ଓ ଗ୍ୟାସ୍ ରିଫିଲ୍',
    probAppItems: [
      'ଏସି ଥଣ୍ଡା ନହେବା / ଗ୍ୟାସ୍ ଲିକେଜ୍',
      'ୱାସିଂ ମେସିନ୍ ମୋଟର ତ୍ରୁଟି',
      'ଫ୍ରିଜ୍ କମ୍ପ୍ରେସର ଗରମ ହେବା ଓ ଥଣ୍ଡା ବନ୍ଦ',
      'ମାଇକ୍ରୋୱେଭ୍ ଓ ଇଣ୍ଡକ୍ସନ ଚୁଲା ମରାମତି'
    ],
    probAppParts: 'ଅରିଜିନାଲ୍ ୪୫uF କାପାସିଟର, R32 ଗ୍ୟାସ୍',

    probCarpTitle: '🔨 କବାଟ, ତାଲା ଓ ଆସବାବପତ୍ର ମରାମତି',
    probCarpSub: 'କାଠ କାର୍ଯ୍ୟ ଓ ଲକ୍ ଫିଟିଂ',
    probCarpItems: [
      'ମୁଖ୍ୟ କବାଟ ତାଲା ଓ ହ୍ୟାଣ୍ଡେଲ ବଦଳାଇବା',
      'ମଡ୍ୟୁଲାର କିଚେନ୍ ହିଞ୍ଜ୍ ମରାମତି',
      'ସୋଫା ଓ ଖଟର କାଠ କାମ',
      'ପ୍ଲାଇଉଡ୍ ପାର୍ଟିସନ ଓ ୱାର୍ଡରୋବ ସ୍ଲାଇଡର'
    ],
    probCarpParts: 'ଗୋଦ୍ରେଜ୍ ବ୍ରାସ୍ ଲକ୍, ଷ୍ଟେନଲେସ୍ ଷ୍ଟିଲ୍ କବ୍ଜା',

    // Rural 1-Tap Action Cards
    ruralSectionBadge: 'ନାଗରିକ ସହାୟତା କେନ୍ଦ୍ର • ଗ୍ରାମୀଣ ଓ ବରିଷ୍ଠ ନାଗରିକ ସୁବିଧା',
    ruralSectionTitle: 'ସମସ୍ତ ନାଗରିକଙ୍କ ପାଇଁ ସହଜ ଓ ସୁଗମ ବୁକିଂ ବ୍ୟବସ୍ଥା',
    callBookingTag: 'ଫୋନରେ ସିଧାସଳଖ ବୁକିଂ',
    callBookingTitle: 'ଟୋଲ୍-ଫ୍ରି କଲ୍ କରନ୍ତୁ',
    callBookingDesc: 'ଇଣ୍ଟରନେଟ୍ ବିନା ସିଧାସଳଖ ଫୋନ୍ ଯୋଗେ ଶ୍ରମିକ ବୁକ୍ କରିବା ପାଇଁ ଡାଏଲ୍ କରନ୍ତୁ:',
    callBookingSub: '୨୪x୭ ମାଗଣା ସେବା →',
    cscBookingTag: 'ଅଫଲାଇନ୍ ସେବା ସହାୟତା',
    cscBookingTitle: 'ଜନ ସେବା କେନ୍ଦ୍ର (CSC)',
    cscBookingDesc: 'ନିଜ ନିକଟସ୍ଥ ପଞ୍ଚାୟତ \'ମୋ ସେବା କେନ୍ଦ୍ର\' (CSC)ରୁ ରସିଦ ସହିତ ବୁକ୍ କରନ୍ତୁ।',
    cscBookingSub: 'ନିକଟସ୍ଥ କେନ୍ଦ୍ର ଦେଖନ୍ତୁ →',
    guaranteeTag: 'ସରକାରୀ ପ୍ରତିଶ୍ରୁତି',
    guaranteeTitle: '୭-ଦିନିଆ ୱାରେଣ୍ଟି',
    guaranteeDesc: 'କାର୍ଯ୍ୟରେ ତ୍ରୁଟି ଥିଲେ ୭ ଦିନ ମଧ୍ୟରେ ବରିଷ୍ଠ ମାଷ୍ଟର ଶ୍ରମିକଙ୍କ ଦ୍ୱାରା ₹୦ରେ ସୁଧାର।',
    guaranteeSub: '୧୦୦% ସରକାରୀ ଗ୍ୟାରେଣ୍ଟି',
    emergencyTag: 'ଜରୁରୀକାଳୀନ ଅଗ୍ରାଧିକାର',
    emergencyTitle: '୨୪/୭ ଜରୁରୀକାଳୀନ ସେବା',
    emergencyDesc: 'ସର୍ଟ ସର୍କିଟ୍ ବା ମୁଖ୍ୟ ପାଇପ୍ ଫାଟିଗଲେ ୩୦ ମିନିଟ୍ ମଧ୍ୟରେ ଶ୍ରମିକ ବଣ୍ଟନ।',
    emergencySub: 'ଜରୁରୀକାଳୀନ ବୁକିଂ →',

    // Categories / Services Section
    secServices: 'ମାନକୀକୃତ ସାର୍ବଜନୀନ ସେବା',
    secServicesSub: 'ପ୍ରମାଣିତ ବାଣିଜ୍ୟ ପ୍ରମାଣପତ୍ର ସହିତ ସ୍ୱଚ୍ଛ ସରକାରୀ-ନିୟନ୍ତ୍ରିତ ମୂଲ୍ୟ ନିର୍ଦ୍ଧାରଣ',
    catElectrical: 'ବିଦ୍ୟୁତ୍ ମରାମତି ଓ ୱେୟାରିଂ',
    catPlumbing: 'ପ୍ଲମ୍ବିଂ / ନଳକୂପ କାର୍ଯ୍ୟ',
    catCarpentry: 'କାଠ କାର୍ଯ୍ୟ ଓ ଆସବାବପତ୍ର',
    catPainting: 'ରଙ୍ଗ କାର୍ଯ୍ୟ (ପେଣ୍ଟିଂ)',
    catCleaning: 'ସଫେଇ ଓ ପରିମଳ ସେବା',
    catGardening: 'ବଗିଚା ରକ୍ଷଣାବେକ୍ଷଣ',
    catCaregiving: 'ବୃଦ୍ଧ ଓ ରୋଗୀ ଯତ୍ନ ସେବା',
    catDriving: 'ଡ୍ରାଇଭର ସେବା',
    catAppliance: 'ଏସି ଓ ଉପକରଣ ମରାମତି',
    catDomestic: 'ଘରୋଇ ସହାୟତା ଓ ରୋଷେଇ',
    catTechnician: 'ସିସିଟିଭି ଓ ଆଇଟି ଟେକ୍ନିସିଆନ୍',
    catEmergency: '୨୪/୭ ଜରୁରୀକାଳୀନ ସେବା',

    descElectrical: 'ୱେୟାରିଂ, ସର୍ଟ ସର୍କିଟ୍, ଇନଭର୍ଟର ଓ ସୁଇଚବୋର୍ଡ ମରାମତି',
    descPlumbing: 'ପାଇପ୍ ଫିଟିଂ, ମୋଟର ପମ୍ପ, ଲିକେଜ୍ ଓ ଡ୍ରେନେଜ୍ ସଫେଇ',
    descCarpentry: 'ଆସବାବପତ୍ର ମରାମତି, କବାଟ ଲକ୍ ଓ କାଠ କାର୍ଯ୍ୟ',
    descPainting: 'ଘର ଭିତର ଓ ବାହାର ରଙ୍ଗ, ପୁଟି ଓ ୱାଟରପ୍ରୁଫିଂ',
    descCleaning: 'ଘରର ଗଭୀର ସଫେଇ, ରୋଷେଇ ଘର ଓ ପାଣି ଟାଙ୍କି ସଫା',
    descAppliance: 'ଏସି ସର୍ଭିସିଂ, ଫ୍ରିଜ୍ ଓ ୱାସିଂ ମେସିନ୍ ମରାମତି',
    descGardening: 'ଘାସ କଟା, ଗଛର ଯତ୍ନ ଓ ବଗିଚା ସୌନ୍ଦର୍ଯ୍ୟକରଣ',
    descCaregiving: 'ବୃଦ୍ଧବୃଦ୍ଧାଙ୍କ ସେବା, ରୋଗୀ ସହାୟତା ଓ ନର୍ସିଂ',
    descDriving: 'ପ୍ରମାଣିତ ବ୍ୟକ୍ତିଗତ ଓ ବ୍ୟବସାୟିକ ଗାଡ଼ି ଚାଳକ',
    descDomestic: 'ଘରୋଇ ସହାୟକ, ରୋଷେଇଆ ଓ ଘରୋଇ କାର୍ଯ୍ୟ',
    descTechnician: 'ସିସିଟିଭି କ୍ୟାମେରା ସେଟଅପ୍, ୱାଇ-ଫାଇ ଓ କମ୍ପ୍ୟୁଟର ମରାମତି',
    descEmergency: '୩୦ ମିନିଟ୍ ମଧ୍ୟରେ ତ୍ୱରିତ ଜରୁରୀକାଳୀନ ସେବା',

    startingAt: 'ପ୍ରାରମ୍ଭିକ ମୂଲ୍ୟ',
    verifiedArtisans: 'ପ୍ରମାଣିତ କାରିଗର',
    viewArtisansBtn: 'ଶ୍ରମିକ',
    bookBtn: 'ବୁକ୍ କରନ୍ତୁ',
    viewAllTariffsBtn: 'ସମସ୍ତ ୧୨ ସେବାର ସରକାରୀ ଦର ଦେଖନ୍ତୁ',

    // 3-Step Simple Guide
    howItWorksBadge: 'ସରଳ ଓ ସୁରକ୍ଷିତ ପ୍ରକ୍ରିୟା • ୩-ପର୍ଯ୍ୟାୟ ବିଶିଷ୍ଟ ବୁକିଂ',
    howItWorksTitle: 'ଘରେ ବସି ସରକାରୀ ପ୍ରମାଣିତ ଶ୍ରମିକ କିପରି ଡାକିବେ?',
    howItWorksSub: 'ପାରଦର୍ଶୀ ସରକାରୀ ପ୍ରକ୍ରିୟା ଦ୍ୱାରା ନିରାପଦ ସେବା ପାଆନ୍ତୁ।',
    step1Title: 'ସମସ୍ୟା ଓ ସେବା ଚୟନ',
    step1Desc: 'ୱେବସାଇଟରେ ସେବା ବାଛନ୍ତୁ ବା କହି ସମସ୍ୟା ଜଣାନ୍ତୁ। ସ୍ଥିର ସରକାରୀ ମୂଲ୍ୟ ତୁରନ୍ତ ଦେଖିପାରିବେ।',
    step2Title: 'ସମୟ ଓ ଠିକଣା ନିର୍ଦ୍ଧାରଣ',
    step2Desc: 'ନିଜ ସୁବିଧା ଅନୁଯାୟୀ ସମୟ ଚୟନ କରନ୍ତୁ। ନିକଟସ୍ଥ ପ୍ରମାଣିତ ଶ୍ରମିକ ନିଯୁକ୍ତ ହେବେ।',
    step3Title: 'ସୁରକ୍ଷିତ କାର୍ଯ୍ୟ ଓ ବିଲ୍',
    step3Desc: 'ପରିଚୟ ପତ୍ର ଓ ଓଟିପି ଯାଞ୍ଚ ସହିତ ଶ୍ରମିକ ପହଞ୍ଚିବେ। କାର୍ଯ୍ୟ ଶେଷରେ ଫର୍ମ IV ବିଲ୍ ପ୍ରାପ୍ତ କରନ୍ତୁ।',

    // Stats Section
    welfareHeading: 'ପ୍ରତ୍ୟେକ ଶ୍ରମିକଙ୍କ ପାଇଁ ୧୦୦% ସାମାଜିକ ସୁରକ୍ଷା',
    welfareSub: 'ପ୍ରତ୍ୟେକ ଅର୍ଡର ସିଧାସଳଖ ପଞ୍ଜୀକୃତ ଶ୍ରମିକମାନଙ୍କ ସ୍ୱାସ୍ଥ୍ୟ ବୀମା, ଦୁର୍ଘଟଣା ସୁରକ୍ଷା ଏବଂ ପେନସନକୁ ସାହାଯ୍ୟ କରେ।',
    statVerifiedWorkers: 'ପ୍ରମାଣିତ କାରିଗର',
    statCooperatives: 'ସକ୍ରିୟ ସମବାୟ ମହାସଂଘ',
    statJobsCompleted: 'ସମ୍ପନ୍ନ ହୋଇଥିବା କାର୍ଯ୍ୟ',
    statSatisfaction: 'ନାଗରିକ ସନ୍ତୋଷ ହାର',

    // Worker Onboarding Banner
    workerCampaignBadge: '👷 କୁଶଳୀ ଶ୍ରମିକ ପଞ୍ଜୀକରଣ ଅଭିଯାନ',
    workerCampaignTitle: 'ଆପଣ ଜଣେ କୁଶଳୀ ଶ୍ରମିକ କି? ଆଜି ହିଁ ଯୋଡ଼ି ହୁଅନ୍ତୁ!',
    workerCampaignDesc: 'ନିଜ ଆଞ୍ଚଳିକ ଶ୍ରମ ସମବାୟ ମହାସଂଘ ସହିତ ଯୋଗ ଦିଅନ୍ତୁ ଏବଂ ପାଆନ୍ତୁ ଶୂନ କମିଶନ, ୧୦୦% ସ୍ୱାସ୍ଥ୍ୟ ବୀମା, ପେନସନ ପାଣ୍ଠି ଓ ସମ୍ମାନଜନକ ଦୈନିକ ଆୟ।',
    workerJoinBtn: 'ଶ୍ରମିକ ପଞ୍ଜୀକରଣ କରନ୍ତୁ →',

    // Navigation Links
    navHome: 'ମୂଳ ପୃଷ୍ଠା',
    navServices: 'ସେବା ସମୂହ',
    navFindWorker: 'ଶ୍ରମିକ ଖୋଜନ୍ତୁ',
    navBookService: 'ସେବା ବୁକ୍ କରନ୍ତୁ',
    navAbout: 'ଆମ ବିଷୟରେ',
    navHelp: 'ସହାୟତା',

    // Common Buttons
    btnCancel: 'ବାତିଲ କରନ୍ତୁ',
    btnPrintBill: 'ଫର୍ମ IV ବିଲ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    btnViewTimeline: 'କାର୍ଯ୍ୟ ଅଗ୍ରଗତି ଦେଖନ୍ତୁ',
    btnPay: 'ଦେୟ ପ୍ରଦାନ କରନ୍ତୁ',
    btnSubmit: 'ଦାଖଲ କରନ୍ତୁ',

    findWorkerBadge: 'ପ୍ରମାଣିତ ସମବାୟ ଶ୍ରମିକ ନିର୍ଦ୍ଦେଶିକା',
    findWorkerTitle: 'ସତ୍ୟାପିତ ସମବାୟ ଶ୍ରମିକ ଖୋଜନ୍ତୁ',
    findWorkerSub: 'ସମସ୍ତ ଜିଲ୍ଲାରେ ପଞ୍ଜୀକୃତ ଶ୍ରମ ସମବାୟ ସଂଘର ପ୍ରମାଣିତ ପେଶାଦାରମାନଙ୍କୁ ଖୋଜନ୍ତୁ।',
    voiceSearchTitle: 'କହି ଖୋଜନ୍ତୁ',
    tradeLabel: 'ବୃତ୍ତି',
    districtLabel: 'ଜିଲ୍ଲା',
    statusLabel: 'ସ୍ଥିତି',
    allTrades: 'ସମସ୍ତ ବୃତ୍ତି',
    allDistricts: 'ସମସ୍ତ ଜିଲ୍ଲା',
    anyStatus: 'ଯେକୌଣସି ସ୍ଥିତି',
    statusAvailable: 'ଉପଲବ୍ଧ',
    statusBusy: 'ବ୍ୟସ୍ତ',
    statusOffline: 'ଅଫଲାଇନ୍',
    verifiedOnly: 'କେବଳ ସତ୍ୟାପିତ',
    resetFilters: 'ସମସ୍ତ ଫିଲ୍ଟର ରିସେଟ୍ କରନ୍ତୁ',
    verified: 'ସତ୍ୟାପିତ',
    pending: 'ବିଚାରାଧୀନ',
    viewProfile: 'ବିବରଣୀ ଦେଖନ୍ତୁ',
    noWorkersFound: 'ଆପଣଙ୍କ ଖୋଜରୁ କୌଣସି ଶ୍ରମିକ ମିଳିଲା ନାହିଁ।',
    loadingWorkers: 'ସତ୍ୟାପିତ ସମବାୟ ଶ୍ରମିକ ଲୋଡ୍ ହେଉଛି...',
    bookThisArtisan: 'ଏହି ଶ୍ରମିକଙ୍କୁ ବୁକ୍ କରନ୍ତୁ',
    coopAffiliation: 'ସମବାୟ ସଂବନ୍ଧ',
    primaryTrade: 'ମୁଖ୍ୟ ବୃତ୍ତି',
    experience: 'ଅଭିଜ୍ଞତା',
    rating: 'ରେଟିଂ',
    completed: 'ସମ୍ପନ୍ନ',
    years: 'ବର୍ଷ',
    artisanBio: 'ଶ୍ରମିକ ପରିଚୟ',
    close: 'ବନ୍ଦ କରନ୍ତୁ',

    servicesDirectoryBadge: 'ମାନକୀକୃତ ସରକାରୀ ସେବା ଦର ତାଲିକା',
    zeroSurgeBannerTitle: 'ଶୂନ୍ୟ ଅତିରିକ୍ତ ଶୁଳ୍କ ଗ୍ୟାରେଣ୍ଟି',
    zeroSurgeBannerDesc: 'ସମସ୍ତ ମୂଲ୍ୟ ରାଜ୍ୟ ସମବାୟ ସଂଘ ଦ୍ୱାରା ମାନକୀକୃତ। କୌଣସି ଲୁକ୍କାୟିତ ଶୁଳ୍କ ନାହିଁ।',
    tollFreeBookingLabel: 'ଟୋଲ୍-ଫ୍ରି ଫୋନ ବୁକିଂ',
    searchServicesPlaceholder: 'ସେବା ଖୋଜନ୍ତୁ (ଯଥା, ବିଦ୍ୟୁତ୍ ମରାମତି, ଲିକେଜ୍, ସଫେଇ)...',
    categoryLabel: 'ଶ୍ରେଣୀ',
    allCategories: 'ସମସ୍ତ ସେବା',
    clearFilters: 'ଫିଲ୍ଟର ସଫା କରନ୍ତୁ',
    loadingServices: 'ସମବାୟ ସେବା ତାଲିକା ଲୋଡ୍ ହେଉଛି...',
    noServicesFound: 'ଆପଣଙ୍କ ଖୋଜରୁ କୌଣସି ସେବା ମିଳିଲା ନାହିଁ।',
    viewWorkers: 'ଶ୍ରମିକ ଦେଖନ୍ତୁ',
    verifiedWorkerCount: 'ସତ୍ୟାପିତ ଶ୍ରମିକ',
    coopBaseRate: 'ସମବାୟ ମୂଳ ଦର',
    priorityEmergency: '୨୪/୭ ଜରୁରୀକାଳୀନ ସେବା',
    responseTime: '୩୦ ମିନିଟ୍ ପ୍ରତିକ୍ରିୟା',

    myBookingsTitle: 'ମୋ ସେବା ବୁକିଂ',
    myBookingsSub: 'ଆପଣଙ୍କ ଘରୋଇ ସେବା ଅର୍ଡର ଟ୍ରାକ ଓ ପରିଚାଳନା କରନ୍ତୁ',
    bookNewService: 'ନୂଆ ସେବା ବୁକ୍ କରନ୍ତୁ',
    tabAll: 'ସମସ୍ତ',
    tabActive: 'ସକ୍ରିୟ',
    tabCompleted: 'ସମ୍ପନ୍ନ',
    tabCancelled: 'ବାତିଲ',
    statusRequested: 'ଅନୁରୋଧ ଗ୍ରହଣ',
    statusMatched: 'ଶ୍ରମିକ ନିଯୁକ୍ତ',
    statusAccepted: 'ଗ୍ରହଣ କରାଯାଇଛି',
    statusInProgress: 'କାର୍ଯ୍ୟ ଚାଲୁ ଅଛି',
    statusCompleted: 'ସଫଳତାର ସହ ସମ୍ପନ୍ନ',
    statusCancelled: 'ବାତିଲ',
    confirmCancel: 'ଆପଣ ନିଶ୍ଚିତ କି ଏହି ବୁକିଂ ବାତିଲ କରିବାକୁ ଚାହୁଁଛନ୍ତି?',
    noBookings: 'କୌଣସି ବୁକିଂ ମିଳିଲା ନାହିଁ।',
    bookFirstService: 'ଆରମ୍ଭ କରିବାକୁ ଆପଣଙ୍କ ପ୍ରଥମ ସେବା ବୁକ୍ କରନ୍ତୁ।',
    warrantyBadge: '୭-ଦିନିଆ ମାଗଣା ମରାମତି ଗ୍ୟାରେଣ୍ଟି',
    warrantySub: 'କାର୍ଯ୍ୟରେ ତ୍ରୁଟି ଥିଲେ ୭ ଦିନ ମଧ୍ୟରେ ମାଷ୍ଟର ଶ୍ରମିକଙ୍କ ଦ୍ୱାରା ₹୦ରେ ସୁଧାର।',

    catElectrical: 'ବିଦ୍ୟୁତ୍',
    catPlumbing: 'ନଳସାଜୀ',
    catCarpentry: 'କାଠ କାମ',
    catPainting: 'ରଙ୍ଗ',
    catCleaning: 'ସଫେଇ',
    catGardening: 'ବାଗିଚା',
    catCaregiving: 'ଯତ୍ନ',
    catDriving: 'ଚାଲକ',
    catAppliance: 'ଉପକରଣ ମରାମତି',
    catDomestic: 'ଘରେଲୂ ସେବା',
    catTechnician: 'IT / ତକନୀଶିୟନ',
    searchBtn: 'ଖୋଜନ୍ତୁ',
    resetAllFilters: 'ସମସ୍ତ ଫିଲ୍ଟର ରିସେଟ୍ କରନ୍ତୁ',

    problemSearchTitle: 'ସମସ୍ୟା ଖୋଜ ଓ ସରକାରୀ ଦର ତାଲିକା',
    problemSearchSub: 'ଆପଣଙ୍କ ମରାମତି ସମସ୍ୟା ଲେଖନ୍ତୁ କିମ୍ବା ତଳେ ଥିବା ବିକଳ୍ପ ବାଛନ୍ତୁ',
    problemSearchDesc: 'ଆମର ପୋର୍ଟାଲ ଆପଣଙ୍କ ଆବଶ୍ୟକତାକୁ ତୁରନ୍ତ ପ୍ରମାଣିତ ସରକାରୀ ଦର ସହିତ ସଂଯୋଗ କରେ।',
    searchIssuePlaceholder: 'ସମସ୍ୟା ଲେଖନ୍ତୁ (ଯଥା ନଳରୁ ପାଣି ପଡିବା, ପଙ୍ଖା ଖରାପ, ଏସି ଗ୍ୟାସ)...',
    btnFindServiceRate: 'ସେବା ଓ ଦର ଖୋଜନ୍ତୁ',
    matchedService: 'ସଂପୃକ୍ତ ସେବା',
    govStandardRate: 'ସରକାରୀ ନିୟନ୍ତ୍ରିତ ଦର',
    orSelectManual: 'କିମ୍ବା ସମସ୍ତ ମାନକୀକୃତ ସରକାରୀ ସେବାରୁ ବାଛନ୍ତୁ',
    matchingServicesFound: 'ମେଳ ଖାଉଥିବା ସେବା ମିଳିଲା',
    clearSearch: 'ଖୋଜ ସଫା କରନ୍ତୁ',
    btnContinueQuote: 'ଚୟନିତ ସେବା ସହିତ ଆଗକୁ ବଢ଼ନ୍ତୁ',
  },

  BN: {
    // Top Bar & Branding
    govSupportTag: 'ভারত সরকার ও সমবায় মন্ত্রণালয় সমর্থিত',
    portalSubHeader: 'ভারত সরকার • শ্রম সমবায় ফেডারেশন পোর্টাল',
    brandName: 'শ্রম সেতু',
    brandSubtitle: 'সমবায় গিগ সেবা প্ল্যাটফর্ম',
    tollFreeLabel: 'টোল-ফ্রি হেল্পলাইন',
    listenVoice: 'শুনুন',
    stopVoice: 'থামুন',
    contrastBtn: 'কন্ট্রাস্ট',
    loginBtn: 'লগইন',
    registerBtn: 'নিবন্ধন',
    dashboardBtn: 'ড্যাশবোর্ড',
    signOutBtn: 'সাইন আউট',

    // Live Ticker
    tickerLabel: 'সরাসরি বিজ্ঞপ্তি',
    tickerText: 'সকল ৩০টি জেলায় ১০০% আইটিআই ও পুলিশ যাচাইকৃত কর্মী উপলব্ধ • সরকারি নিয়ন্ত্রিত মূল্য • ৭-দিনের বিনামূল্যের মেরামত ওয়ারেন্টি • কল করুন: ১৮০০-৩৪৫-৭৭৮৮',

    // Hero Section
    heroTitlePart1: 'যাচাইকৃত ট্রেড দক্ষতা।',
    heroTitlePart2: 'ন্যায্য সরকারি মূল্য।',
    heroTitlePart3: 'শক্তিশালী শ্রমিক সমাজ।',
    heroSubtitle: 'আঞ্চলিক শ্রম সমবায় ফেডারেশনের সাথে যুক্ত দক্ষ ও যাচাইকৃত পেশাদারদের সাথে সংযোগ করুন। সরকারি নিয়ন্ত্রিত মূল্য, অতিরিক্ত চার্জ নেই এবং সামাজিক নিরাপত্তা।',
    btnBookNow: 'সেবা বুক করুন',
    btnFindWorker: 'কর্মী খুঁজুন',
    btnJoinWorker: 'আপনি কি একজন দক্ষ কর্মী? আপনার স্থানীয় সমবায়ে যোগ দিন →',

    // Quick Booking Console (Hero)
    quickSearchTitle: 'দ্রুত কর্মী সন্ধান ও বুকিং',
    liveDispatchActive: 'সরাসরি বরাদ্দ সক্রিয়',
    selectServiceLabel: '১. সেবা নির্বাচন করুন',
    selectDistrictLabel: '২. জেলা নির্বাচন করুন',
    enterProblemLabel: '৩. সমস্যা লিখুন বা বলুন',
    searchBtn: 'অনুসন্ধান',
    allServicesOption: '-- সকল ১২টি পরিষেবা --',
    quickTagsLabel: 'দ্রুত:',

    // Floating Hero Cards
    nearbyArtisanTag: 'নিকটতম যাচাইকৃত কর্মী',
    fixedRateTag: 'স্থির মূল হার',
    sampleWorkerName: 'রমেশ কুমার',
    sampleWorkerRole: 'মাস্টার ইলেকট্রিশিয়ান • ITI Gold Certified',
    sampleWorkerStats: '১২৪+ কাজ সম্পন্ন • ১.২ কিমি দূরে',
    policeVerifiedBadge: 'পুলিশ ও আধার যাচাইকৃত',
    bookNowShort: 'বুক করুন →',
    guaranteeCardTitle: '৭-দিনের সরকারি মেরামত ওয়ারেন্টি',
    guaranteeCardDesc: 'কাজে কোনো ত্রুটি থাকলে ৭ দিনের মধ্যে মাস্টার কর্মী দ্বারা ₹০ খরচে বিনামূল্যে সমাধান।',
    welfareCardTitle: '১০০% কর্মী সামাজিক নিরাপত্তা',
    welfareCardDesc: 'প্রতিটি বুকিং থেকে সরাসরি ১০% অর্থ কর্মীর স্বাস্থ্য ও পেনশন তহবিলে জমা হয়।',

    // Trust Pillars (Hero bottom)
    pillar1Title: '১০০% যাচাইকৃত কর্মী',
    pillar1Desc: 'ITI / NSDC ও পুলিশ যাচাইকৃত',
    pillar2Title: 'অতিরিক্ত চার্জ নেই',
    pillar2Desc: 'সরকারি নিয়ন্ত্রিত মূল হার',
    pillar3Title: '১০০% সামাজিক নিরাপত্তা',
    pillar3Desc: 'স্বাস্থ্য ও পেনশন সুরক্ষা কভার',

    // Problem Matcher Section
    problemMatcherBadge: 'স্মার্ট সমস্যা নির্ণয়',
    problemMatcherTitle: 'বাড়িতে কী সমস্যা? তাৎক্ষণিক সমাধান পান',
    tabElectrical: '⚡ বিদ্যুৎ',
    tabPlumbing: '🚰 প্লাম্বিং',
    tabAppliance: '❄️ এসি / ফ্রিজ',
    tabCarpentry: '🔨 কাঠের কাজ / তালা',
    likelyPartsLabel: 'সম্ভাব্য মানক সামগ্রী:',
    baseRateTag: 'মানক শ্রম মূল হার:',
    zeroSurgeNotice: '✓ কোনো অতিরিক্ত মূল্য নেই • ফর্ম IV ট্যাক্স বিল • ৭-দিনের ওয়ারেন্টি',
    bookThisServiceBtn: 'এখনই সেবাটি বুক করুন',

    // Problem Items
    probElecTitle: '⚡ বৈদ্যুতিক ও ওয়্যারিং সমস্যা',
    probElecSub: 'বৈদ্যুতিক ত্রুটি ও শর্ট সার্কিট',
    probElecItems: [
      'MCB বারবার ট্রিপ হওয়া বা স্পার্কিং',
      'ইনভার্টার ও ইউপিএস ত্রুটি',
      'সুইচবোর্ড, ফ্যান ও লাইট মেরামত',
      'গিজার ও প্রধান লাইন ওয়্যারিং'
    ],
    probElecParts: 'ISI মার্ক কপার ওয়্যার, হ্যাভেলস MCB, অ্যাঙ্কর সুইচ',

    probPlumbTitle: '🚰 প্লাম্বিং ও জল লিকেজ সমস্যা',
    probPlumbSub: 'পাইপলাইন ও স্যানিটারি কাজ',
    probPlumbItems: [
      'কিচেন সিঙ্ক ও বেসিনের নিচ থেকে জল পড়া',
      'জলের ট্যাঙ্ক উপচে পড়া / ভালভ জ্যাম',
      'মোটর পাম্প মেরামত ও নতুন ফিটিং',
      'ভূগর্ভস্থ পাইপ লিকেজ ও ড্রেনেজ সমস্যা'
    ],
    probPlumbParts: 'অ্যাস্ট্রাল CPVC পাইপ, ব্রাস বল ভালভ',

    probAppTitle: '❄️ এসি, ফ্রিজ ও ওয়াশিং মেশিন',
    probAppSub: 'যন্ত্রপাতি পরীক্ষা ও গ্যাস রিফিল',
    probAppItems: [
      'এসি ঠান্ডা না হওয়া / গ্যাস লিকেজ পরীক্ষা',
      'ওয়াশিং মেশিন মোটর ত্রুটি',
      'ফ্রিজ কম্প্রেসার গরম হওয়া ও ঠান্ডা বন্ধ',
      'মাইক্রোওয়েভ ও ইনডাকশন ওভেন মেরামত'
    ],
    probAppParts: 'অরিজিনাল ৪৫uF ক্যাপাসিটর, R32 গ্যাস',

    probCarpTitle: '🔨 দরজা, তালা ও আসবাবপত্র মেরামত',
    probCarpSub: 'কাঠের কাজ ও তালা ফিটিং',
    probCarpItems: [
      'প্রধান দরজার তালা ও হাতল পরিবর্তন',
      'মডুলার কিচেন কব্জা মেরামত',
      'সোফা ও খাটের কাঠের কাজ',
      'প্লাইউড পার্টিশন ও আলমারি স্লাইডার'
    ],
    probCarpParts: 'গোদরেজ ব্রাস লক, স্টেইনলেস স্টিল কব্জা',

    // Rural 1-Tap Action Cards
    ruralSectionBadge: 'নাগরিক সহায়তা কেন্দ্র • সহজ ও সহায়ক সেবা',
    ruralSectionTitle: 'সকল নাগরিকের জন্য সহজ বুকিং ব্যবস্থা',
    callBookingTag: 'ফোনে সরাসরি বুকিং',
    callBookingTitle: 'টোল-ফ্রি কল করুন',
    callBookingDesc: 'ইন্টারনেট ছাড়াই সরাসরি ফোনে কর্মী বুক করতে ডায়াল করুন:',
    callBookingSub: '২৪x৭ বিনামূল্যে সেবা →',
    cscBookingTag: 'অফলাইন সহায়তা',
    cscBookingTitle: 'জন সেবা কেন্দ্র (CSC)',
    cscBookingDesc: 'আপনার নিকটস্থ পঞ্চায়েত \'মো সেবা কেন্দ্র\' (CSC) থেকে রশিদসহ বুক করুন।',
    cscBookingSub: 'নিকটস্থ কেন্দ্র দেখুন →',
    guaranteeTag: 'সরকারি নিশ্চয়তা',
    guaranteeTitle: '৭-দিনের ওয়ারেন্টি',
    guaranteeDesc: 'কাজে ত্রুটি থাকলে ৭ দিনের মধ্যে মাস্টার কর্মী দ্বারা বিনামূল্যে সমাধান।',
    guaranteeSub: '১০০% সরকারি গ্যারান্টি',
    emergencyTag: 'জরুরি অগ্রাধিকার',
    emergencyTitle: '২৪/৭ জরুরি পরিষেবা',
    emergencyDesc: 'শর্ট সার্কিট বা পাইপ ফাটলে ৩০ মিনিটের মধ্যে অগ্রাধিকার ভিত্তিতে বরাদ্দ।',
    emergencySub: 'জরুরি বুকিং →',

    // Categories / Services Section
    secServices: 'মানক সার্বজনীন পরিষেবা',
    secServicesSub: 'স্বচ্ছ সরকারি নিয়ন্ত্রিত মূল্য এবং যাচাইকৃত ট্রেড শংসাপত্র',
    catElectrical: 'বৈদ্যুতিক মেরামত ও ওয়্যারিং',
    catPlumbing: 'প্লাম্বিং ও পাইপ ফিটিং',
    catCarpentry: 'কাঠের কাজ ও আসবাবপত্র',
    catPainting: 'পেইন্টিং ও ওয়াল ফিনিশিং',
    catCleaning: 'পরিচ্ছন্নতা ও স্যানিটেশন',
    catGardening: 'বাগান পরিচর্যা',
    catCaregiving: 'সেবাযত্ন ও পরিচর্যা',
    catDriving: 'ড্রাইভার সেবা',
    catAppliance: 'এসি ও যন্ত্রপাতি মেরামত',
    catDomestic: 'গৃহস্থালি সাহায্য ও রান্না',
    catTechnician: 'সিসিটিভি ও আইটি প্রযুক্তিবিদ',
    catEmergency: '২৪/৭ জরুরি পরিষেবা',

    descElectrical: 'ওয়্যারিং, শর্ট সার্কিট, ইনভার্টার ও সুইচবোর্ড',
    descPlumbing: 'পাইপ ফিটিং, মোটর পাম্প ও ড্রেনেজ মেরামত',
    descCarpentry: 'আসবাবপত্র মেরামত ও কাঠের কাজ',
    descPainting: 'অভ্যন্তরীণ ও বহিরাগত পেইন্টিং',
    descCleaning: 'বাড়ি এবং জলের ট্যাঙ্ক গভীর পরিচ্ছন্নতা',
    descAppliance: 'এসি, ফ্রিজ ও ওয়াশিং মেশিন মেরামত',
    descGardening: 'বাগান ও লন পরিচর্যা',
    descCaregiving: 'বয়স্কদের সেবা ও নার্সিং সহায়তা',
    descDriving: 'যাচাইকৃত পেশাদার গাড়ি চালক',
    descDomestic: 'গৃহকর্মী ও রান্নার সাহায্য',
    descTechnician: 'সিসিটিভি ক্যামেরা ও কম্পিউটার মেরামত',
    descEmergency: '৩০ মিনিটের মধ্যে জরুরি সেবা',

    startingAt: 'প্রারম্ভিক মূল্য',
    verifiedArtisans: 'যাচাইকৃত কারিগর',
    viewArtisansBtn: 'কর্মী',
    bookBtn: 'বুক করুন',
    viewAllTariffsBtn: 'সকল ১২টি সেবার সরকারি দর দেখুন',

    // 3-Step Simple Guide
    howItWorksBadge: 'সহজ ও নিরাপদ প্রক্রিয়া • ৩-ধাপে বুকিং',
    howItWorksTitle: 'ঘরে বসে সরকারি যাচাইকৃত কর্মী কীভাবে ডাকবেন?',
    howItWorksSub: 'স্বচ্ছ সরকারি প্রক্রিয়ায় নিরাপদ সেবা নিশ্চিত করুন।',
    step1Title: 'সমস্যা ও সেবা নির্বাচন',
    step1Desc: 'ওয়েবসাইটে সেবা নির্বাচন করুন বা মুখে বলুন। নির্ধারিত সরকারি মূল্য তাৎক্ষণিক দেখা যাবে।',
    step2Title: 'সময় ও ঠিকানা নির্ধারণ',
    step2Desc: 'আপনার সুবিধাজনক সময় নির্বাচন করুন। নিকটতম সমবায় কর্মী নিযুক্ত হবেন।',
    step3Title: 'নিরাপদ কাজ ও সরকারি বিল',
    step3Desc: 'কর্মী পরিচয়পত্র ও ওটিপি যাচাইসহ পৌঁছাবেন। কাজ শেষে ফর্ম IV বিল গ্রহণ করুন।',

    // Stats Section
    welfareHeading: 'প্রত্যেক কর্মীর জন্য ১০০% সামাজিক নিরাপত্তা',
    welfareSub: 'প্রতিটি বুকিং সরাসরি নিবন্ধিত সমবায় কর্মীদের স্বাস্থ্য বীমা ও পেনশনে সহায়তা করে।',
    statVerifiedWorkers: 'যাচাইকৃত কারিগর',
    statCooperatives: 'সক্রিয় ফেডারেশন',
    statJobsCompleted: 'সম্পন্ন কাজ',
    statSatisfaction: 'নাগরিক সন্তুষ্টি হার',

    // Worker Onboarding Banner
    workerCampaignBadge: '👷 দক্ষ কর্মী নিবন্ধন অভিযান',
    workerCampaignTitle: 'আপনি কি একজন দক্ষ কর্মী? আজই যোগ দিন!',
    workerCampaignDesc: 'আপনার স্থানীয় সমবায় ফেডারেশনে যোগ দিন এবং পান ০% কমিশন, ১০০% স্বাস্থ্য বীমা ও সম্মানজনক আয়।',
    workerJoinBtn: 'কর্মী হিসেবে নিবন্ধন করুন →',

    // Navigation Links
    navHome: 'হোম',
    navServices: 'পরিষেবাসমূহ',
    navFindWorker: 'কর্মী খুঁজুন',
    navBookService: 'পরিষেবা বুক করুন',
    navAbout: 'আমাদের সম্পর্কে',
    navHelp: 'সহায়তা',

    // Common Buttons
    btnCancel: 'বাতিল করুন',
    btnPrintBill: 'ফর্ম IV বিল প্রিন্ট করুন',
    btnViewTimeline: 'কাজের অগ্রগতি দেখুন',
    btnPay: 'পেমেন্ট করুন',
    btnSubmit: 'জমা দিন',

    findWorkerBadge: 'প্রত্যয়িত সমবায় কর্মী তালিকা',
    findWorkerTitle: 'যাচাইকৃত সমবায় কর্মী খুঁজুন',
    findWorkerSub: 'সকল জেলায় নিবন্ধিত শ্রম সমবায় ফেডারেশনের প্রত্যয়িত পেশাদারদের খুঁজুন।',
    voiceSearchTitle: 'বলে খুঁজুন',
    tradeLabel: 'পেশা',
    districtLabel: 'জেলা',
    statusLabel: 'অবস্থা',
    allTrades: 'সকল পেশা',
    allDistricts: 'সকল জেলা',
    anyStatus: 'যেকোনো অবস্থা',
    statusAvailable: 'উপলব্ধ',
    statusBusy: 'ব্যস্ত',
    statusOffline: 'অফলাইন',
    verifiedOnly: 'শুধু যাচাইকৃত',
    resetFilters: 'সকল ফিল্টার রিসেট করুন',
    verified: 'যাচাইকৃত',
    pending: 'মুলতুবি',
    viewProfile: 'বিস্তারিত দেখুন',
    noWorkersFound: 'আপনার অনুসন্ধানে কোনো কর্মী পাওয়া যায়নি।',
    loadingWorkers: 'যাচাইকৃত সমবায় কর্মী লোড হচ্ছে...',
    bookThisArtisan: 'এই কারিগরকে বুক করুন',
    coopAffiliation: 'সমবায় সম্পর্ক',
    primaryTrade: 'প্রধান পেশা',
    experience: 'অভিজ্ঞতা',
    rating: 'রেটিং',
    completed: 'সম্পন্ন',
    years: 'বছর',
    artisanBio: 'কারিগরের পরিচয়',
    close: 'বন্ধ করুন',

    servicesDirectoryBadge: 'প্রমিত সরকারি সেবা মূল্য তালিকা',
    zeroSurgeBannerTitle: 'শূন্য অতিরিক্ত চার্জ গ্যারান্টি',
    zeroSurgeBannerDesc: 'সকল মূল্য রাজ্য সমবায় সংঘ দ্বারা নির্ধারিত। কোনো লুকানো চার্জ নেই।',
    tollFreeBookingLabel: 'টোল-ফ্রি ফোন বুকিং',
    searchServicesPlaceholder: 'পরিষেবা খুঁজুন (যেমন, বৈদ্যুতিক মেরামত, লিকেজ, পরিষ্কার)...',
    categoryLabel: 'বিভাগ',
    allCategories: 'সকল পরিষেবা',
    clearFilters: 'ফিল্টার পরিষ্কার করুন',
    loadingServices: 'সমবায় পরিষেবা তালিকা লোড হচ্ছে...',
    noServicesFound: 'আপনার অনুসন্ধানে কোনো পরিষেবা পাওয়া যায়নি।',
    viewWorkers: 'কর্মী দেখুন',
    verifiedWorkerCount: 'যাচাইকৃত কর্মী',
    coopBaseRate: 'সমবায় মূল মূল্য',
    priorityEmergency: '২৪/৭ জরুরি পরিষেবা',
    responseTime: '৩০ মিনিটে প্রতিক্রিয়া',

    myBookingsTitle: 'আমার পরিষেবা বুকিং',
    myBookingsSub: 'আপনার গৃহস্থালি পরিষেবা অর্ডার ট্র্যাক ও পরিচালনা করুন',
    bookNewService: 'নতুন পরিষেবা বুক করুন',
    tabAll: 'সকল',
    tabActive: 'সক্রিয়',
    tabCompleted: 'সম্পন্ন',
    tabCancelled: 'বাতিল',
    statusRequested: 'অনুরোধ গৃহীত',
    statusMatched: 'কর্মী নিয়োগ',
    statusAccepted: 'গৃহীত',
    statusInProgress: 'কাজ চলছে',
    statusCompleted: 'সফলভাবে সম্পন্ন',
    statusCancelled: 'বাতিল',
    confirmCancel: 'আপনি কি নিশ্চিত যে এই বুকিং বাতিল করতে চান?',
    noBookings: 'কোনো বুকিং পাওয়া যায়নি।',
    bookFirstService: 'শুরু করতে আপনার প্রথম পরিষেবা বুক করুন।',
    warrantyBadge: '৭-দিনের বিনামূল্যে মেরামত গ্যারান্টি',
    warrantySub: 'কাজে ত্রুটি থাকলে ৭ দিনের মধ্যে মাস্টার কর্মী দ্বারা ₹০ খরচে সমাধান।',

    catElectrical: 'বৈদ্যুতিক',
    catPlumbing: 'প্লাম্বিং',
    catCarpentry: 'সূত্রধর',
    catPainting: 'রঙ',
    catCleaning: 'পরিষ্কার',
    catGardening: 'বাগান',
    catCaregiving: 'যত্ন',
    catDriving: 'চালক',
    catAppliance: 'যন্ত্র মেরামত',
    catDomestic: 'গৃহস্থালি সেবা',
    catTechnician: 'IT / তকনিশিয়ান',
    searchBtn: 'খুঁজুন',
    resetAllFilters: 'সকল ফিল্টার রিসেট করুন',

    problemSearchTitle: 'সমস্যা অনুসন্ধান ও সরকারি মূল্য তালিকা',
    problemSearchSub: 'আপনার মেরামতের সমস্যা লিখুন বা নিচের বিকল্প থেকে নির্বাচন করুন',
    problemSearchDesc: 'আমাদের পোর্টাল আপনার প্রয়োজনকে অবিলম্বে প্রত্যয়িত সরকারি মূল্যের সাথে যুক্ত করে।',
    searchIssuePlaceholder: 'সমস্যা লিখুন (যেমন জলের কল লিক, পাখা নষ্ট, এসি গ্যাস)...',
    btnFindServiceRate: 'সেবা ও মূল্য খুঁজুন',
    matchedService: 'সম্পর্কিত পরিষেবা',
    govStandardRate: 'সরকারি নির্ধারিত মূল্য',
    orSelectManual: 'বা সকল প্রমিত সরকারি পরিষেবা থেকে বেছে নিন',
    matchingServicesFound: 'সম্পর্কিত পরিষেবা পাওয়া গেছে',
    clearSearch: 'অনুসন্ধান মুছুন',
    btnContinueQuote: 'নির্বাচিত পরিষেবার সাথে এগিয়ে যান',
  },

  TE: {
    // Top Bar & Branding
    govSupportTag: 'భారత ప్రభుత్వం & సహకార మంత్రిత్వ శాఖ మద్దతు',
    portalSubHeader: 'భారత ప్రభుత్వం • లేబర్ కోఆపరేటివ్ ఫెడరేషన్ పోర్టల్',
    brandName: 'శ్రమ్ సేతు',
    brandSubtitle: 'కోఆపరేటివ్ గిగ్ సర్వీసెస్ పోర్టల్',
    tollFreeLabel: 'టోల్-ఫ్రీ హెల్ప్‌లైన్',
    listenVoice: 'వినండి',
    stopVoice: 'ఆపండి',
    contrastBtn: 'కాంట్రాస్ట్',
    loginBtn: 'లాగిన్',
    registerBtn: 'నమోదు',
    dashboardBtn: 'డ్యాష్‌బోర్డ్',
    signOutBtn: 'సైన్ అవుట్',

    // Live Ticker
    tickerLabel: 'ప్రత్యక్ష సమాచారం',
    tickerText: 'అన్ని 30 జిల్లాల్లో 100% ITI మరియు పోలీస్ ధృవీకరించిన కార్మికులు అందుబాటులో ఉన్నారు • ప్రభుత్వ నియంత్రిత ధరలు • 7 రోజుల ఉచిత మరమ్మతు హామీ • కాల్ చేయండి: 1800-345-7788',

    // Hero Section
    heroTitlePart1: 'ధృవీకరించబడిన నైపుణ్యాలు.',
    heroTitlePart2: 'సహకార కార్మికులు.',
    heroTitlePart3: 'బలమైన సమాజం.',
    heroSubtitle: 'ఒడిశా వ్యాప్తంగా ప్రాంతీయ లేబర్ కోఆపరేటివ్ ఫెడరేషన్లతో అనుబంధంగా ఉన్న ధృవీకరించబడిన నైపుణ్యం కలిగిన నిపుణులతో కనెక్ట్ అవ్వండి. నియంత్రిత టారిఫ్‌లు మరియు సామాజిక భద్రత.',
    btnBookNow: 'సేవను బుక్ చేయండి',
    btnFindWorker: 'కార్మికుడిని కనుగొనండి',
    btnJoinWorker: 'మీరు నైపుణ్యం కలిగిన కార్మికులా? మీ స్థానిక సహకార సంఘంలో చేరండి →',

    // Quick Booking Console (Hero)
    quickSearchTitle: 'త్వరిత కార్మికుల శోధన మరియు బుకింగ్',
    liveDispatchActive: 'ప్రత్యక్ష కేటాయింపు సక్రియంగా ఉంది',
    selectServiceLabel: '1. సేవను ఎంచుకోండి',
    selectDistrictLabel: '2. జిల్లాను ఎంచుకోండి',
    enterProblemLabel: '3. సమస్యను రాయండి లేదా మాట్లాడండి',
    searchBtn: 'శోధించండి',
    allServicesOption: '-- అన్ని 12 సేవలు --',
    quickTagsLabel: 'త్వరిత:',

    // Floating Hero Cards
    nearbyArtisanTag: 'సమీపంలోని ధృవీకరించబడిన కార్మికుడు',
    fixedRateTag: 'స్థిరమైన బేస్ ధర',
    sampleWorkerName: 'రమేష్ కుమార్',
    sampleWorkerRole: 'మాస్టర్ ఎలక్ట్రీషియన్ • ITI Gold Certified',
    sampleWorkerStats: '124+ పనులు పూర్తి • 1.2 కి.మీ దూరం',
    policeVerifiedBadge: 'పోలీస్ & ఆధార్ ధృవీకరించబడింది',
    bookNowShort: 'ఇప్పుడే బుక్ చేయండి →',
    guaranteeCardTitle: '7 రోజుల ఉచిత ప్రభుత్వ మరమ్మతు హామీ',
    guaranteeCardDesc: 'పనిలో ఏదైనా లోపం ఉంటే 7 రోజుల్లో మాస్టర్ కార్మికుడి ద్వారా ₹0 ఖర్చుతో ఉచిత పరిష్కారం.',
    welfareCardTitle: '100% కార్మిక సామాజిక భద్రత',
    welfareCardDesc: 'ప్రతి బుకింగ్ నుండి నేరుగా 10% కార్మికుడి ఆరోగ్య & పెన్షన్ నిధికి చేరుతుంది.',

    // Trust Pillars (Hero bottom)
    pillar1Title: '100% ధృవీకరించబడిన కార్మికులు',
    pillar1Desc: 'ITI / NSDC మరియు పోలీస్ ధృవీకరించబడింది',
    pillar2Title: 'అదనపు ఛార్జీలు లేవు',
    pillar2Desc: 'ప్రభుత్వ నియంత్రిత బేస్ టారిఫ్‌లు',
    pillar3Title: '100% సామాజిక భద్రత',
    pillar3Desc: 'ఆరోగ్య & పెన్షన్ భద్రతా కవర్',

    // Problem Matcher Section
    problemMatcherBadge: 'స్మార్ట్ సమస్య నిర్ధారణ',
    problemMatcherTitle: 'ఇంట్లో ఏమి సమస్య ఉంది? తక్షణ పరిష్కారం పొందండి',
    tabElectrical: '⚡ విద్యుత్',
    tabPlumbing: '🚰 ప్లంబింగ్',
    tabAppliance: '❄️ ఏసీ / ఫ్రిజ్',
    tabCarpentry: '🔨 వడ్రంగి / తాళాలు',
    likelyPartsLabel: 'ప్రామాణిక సామగ్రి:',
    baseRateTag: 'ప్రామాణిక లేబర్ బేస్ రేటు:',
    zeroSurgeNotice: '✓ అదనపు ధర లేదు • ఫారం IV బిల్లు • 7 రోజుల వారంటీ',
    bookThisServiceBtn: 'ఈ సేవను ఇప్పుడే బుక్ చేయండి',

    // Problem Items
    probElecTitle: '⚡ విద్యుత్ & వైరింగ్ సమస్యలు',
    probElecSub: 'విద్యుత్ లోపాలు & షార్ట్ సర్క్యూట్లు',
    probElecItems: [
      'MCB పదేపదే ట్రిప్ అవ్వడం లేదా స్పార్కింగ్',
      'ఇన్వర్టర్ & UPS వైరింగ్ లోపాలు',
      'స్విచ్‌బోర్డు, ఫ్యాన్ & లైట్ మరమ్మతు',
      'గీజర్ & మెయిన్ లైన్ వైరింగ్'
    ],
    probElecParts: 'ISI మార్క్ రాగి వైర్, హావెల్స్ MCB, యాంకర్ స్విచ్‌లు',

    probPlumbTitle: '🚰 ప్లంబింగ్ & వాటర్ లీకేజ్ సమస్యలు',
    probPlumbSub: 'పైప్‌లైన్ & శానిటరీ పనులు',
    probPlumbItems: [
      'సింక్ & బేసిన్ కింద నుండి నీరు కారడం',
      'వాటర్ ట్యాంక్ ఓవర్‌ఫ్లో / వాల్వ్ జామ్',
      'మోటార్ పంప్ మరమ్మతు & కొత్త ఫిట్టింగ్',
      'పైప్‌లైన్ లీకేజ్ & డ్రైనేజీ బ్లాక్'
    ],
    probPlumbParts: 'ఆస్ట్రల్ CPVC పైపులు, బ్రాస్ బాల్ వాల్వ్',

    probAppTitle: '❄️ ఏసీ, రిఫ్రిజిరేటర్ & వాషింగ్ మెషిన్',
    probAppSub: 'ఉపకరణాల పరీక్ష & గ్యాస్ రీఫిల్',
    probAppItems: [
      'ఏసీ కూలింగ్ లేకపోవడం / గ్యాస్ లీకేజ్',
      'వాషింగ్ మెషిన్ మోటార్ లోపం',
      'ఫ్రిజ్ కంప్రెసర్ వేడెక్కడం & కూలింగ్ బంద్',
      'మైక్రోవేవ్ & ఇండక్షన్ కుక్కర్ మరమ్మతు'
    ],
    probAppParts: 'ఒరిజినల్ 45uF కెపాసిటర్, R32 గ్యాస్',

    probCarpTitle: '🔨 తలుపులు, తాళాలు & ఫర్నిచర్ మరమ్మతు',
    probCarpSub: 'వడ్రంగి పని & లాక్ ఫిట్టింగ్',
    probCarpItems: [
      'ప్రధాన తలుపు లాక్ & హ్యాండిల్ మార్చడం',
      'మాడ్యులర్ కిచెన్ కీలు మరమ్మతు',
      'సోఫా & మంచం చెక్క పని',
      'ప్లైవుడ్ విభజన & వార్డ్‌రోబ్ స్లైడర్'
    ],
    probCarpParts: 'గోద్రెజ్ బ్రాస్ లాక్, స్టెయిన్‌లెస్ స్టీల్ కీలు',

    // Rural 1-Tap Action Cards
    ruralSectionBadge: 'పౌర సహాయ కేంద్రం • గ్రామీణ & సహాయక సేవలు',
    ruralSectionTitle: 'పౌరులందరికీ సులభమైన మరియు అనుకూలమైన బుకింగ్',
    callBookingTag: 'ఫోన్ ద్వారా నేరుగా బుకింగ్',
    callBookingTitle: 'టోల్-ఫ్రీ కాల్ చేయండి',
    callBookingDesc: 'ఇంటర్నెట్ లేకుండా నేరుగా ఫోన్ ద్వారా బుక్ చేసుకోవడానికి డయల్ చేయండి:',
    callBookingSub: '24x7 ఉచిత సేవ →',
    cscBookingTag: 'ఆఫ్‌లైన్ సహాయం',
    cscBookingTitle: 'జన సేవా కేంద్రం (CSC)',
    cscBookingDesc: 'మీ సమీప పంచాయతీ \'మో సేవా కేంద్రం\' (CSC) నుండి రసీదుతో బుక్ చేయండి.',
    cscBookingSub: 'సమీప కేంద్రాన్ని చూడండి →',
    guaranteeTag: 'ప్రభుత్వ హామీ',
    guaranteeTitle: '7 రోజుల వారంటీ',
    guaranteeDesc: 'పనిలో లోపం ఉంటే 7 రోజుల్లో మాస్టర్ కార్మికుడి ద్వారా ఉచిత పరిష్కారం.',
    guaranteeSub: '100% ప్రభుత్వ హామీ',
    emergencyTag: 'తక్షణ ప్రాధాన్యత',
    emergencyTitle: '24/7 అత్యవసర సేవ',
    emergencyDesc: 'షార్ట్ సర్క్యూట్ లేదా పైప్ పగిలితే 30 నిమిషాల్లో ప్రాధాన్యత కేటాయింపు.',
    emergencySub: 'అత్యవసర బుకింగ్ →',

    // Categories / Services Section
    secServices: 'ప్రామాణిక ప్రజా సేవలు',
    secServicesSub: 'ధృవీకరించబడిన ట్రేడ్ సర్టిఫికేట్‌లతో పారదర్శక ప్రభుత్వ నియంత్రిత ధరలు',
    catElectrical: 'విద్యుత్ మరమ్మతు & వైరింగ్',
    catPlumbing: 'ప్లంబింగ్ & పైప్ ఫిట్టింగ్',
    catCarpentry: 'వడ్రంగి & ఫర్నిచర్',
    catPainting: 'పెయింటింగ్ & వాల్ కోటింగ్',
    catCleaning: 'డీప్ క్లీనింగ్ & శానిటేషన్',
    catGardening: 'గార్డెనింగ్ & ల్యాండ్‌స్కేపింగ్',
    catCaregiving: 'వృద్ధులు & రోగుల సంరక్షణ',
    catDriving: 'వాహన డ్రైవర్ సేవలు',
    catAppliance: 'ఏసీ & ఉపకరణాల మరమ్మతు',
    catDomestic: 'గృహ సహాయం & వంట',
    catTechnician: 'CCTV & IT టెక్నీషియన్',
    catEmergency: '24/7 అత్యవసర సేవలు',

    descElectrical: 'వైరింగ్, షార్ట్ సర్క్యూట్, ఇన్వర్టర్ & స్విచ్‌బోర్డ్',
    descPlumbing: 'పైప్ ఫిట్టింగ్, మోటార్ పంప్, లీకేజ్ & డ్రైనేజ్',
    descCarpentry: 'ఫర్నిచర్ మరమ్మతు, తలుపు తాళాలు & చెక్క పని',
    descPainting: 'ఇంటీరియర్, ఎక్స్‌టీరియర్, పుట్టీ & వాటర్‌ప్రూఫింగ్',
    descCleaning: 'ఇంటి డీప్ క్లీనింగ్, కిచెన్ & ట్యాంక్ క్లీనింగ్',
    descAppliance: 'ఏసీ సర్వీసింగ్, రిఫ్రిజిరేటర్ & వాషింగ్ మెషిన్',
    descGardening: 'లాన్ కట్టింగ్, మొక్కల సంరక్షణ & గార్డెనింగ్',
    descCaregiving: 'వృద్ధుల సంరక్షణ, రోగుల సహాయం & నర్సింగ్',
    descDriving: 'ధృవీకరించబడిన ప్రైవేట్ మరియు వాణిజ్య డ్రైవర్లు',
    descDomestic: 'ఇంటి సహాయకులు, వంటవారు & హౌస్‌కీపింగ్',
    descTechnician: 'CCTV కెమెరా, వై-ఫై & కంప్యూటర్ మరమ్మతు',
    descEmergency: '30 నిమిషాల్లో తక్షణ ప్రాధాన్యత సేవ',

    startingAt: 'ప్రారంభ ధర',
    verifiedArtisans: 'ధృవీకరించబడిన కార్మికులు',
    viewArtisansBtn: 'కార్మికులు',
    bookBtn: 'బుక్ చేయండి',
    viewAllTariffsBtn: 'అన్ని 12 సేవల ప్రభుత్వ ధరల జాబితాను చూడండి',

    // 3-Step Simple Guide
    howItWorksBadge: 'సులభమైన & సురక్షితమైన ప్రక్రియ • 3-దశల బుకింగ్',
    howItWorksTitle: 'ఇంటి నుండే ప్రభుత్వ ధృవీకరించిన కార్మికుడిని ఎలా పిలవాలి?',
    howItWorksSub: 'పారదర్శక ప్రభుత్వ ప్రక్రియ ద్వారా సురక్షితమైన సేవను పొందండి.',
    step1Title: 'సమస్య & సేవను ఎంచుకోండి',
    step1Desc: 'వెబ్‌సైట్‌లో సేవను ఎంచుకోండి లేదా మాట్లాడి చెప్పండి. స్థిరమైన ప్రభుత్వ ధర తక్షణమే కనిపిస్తుంది.',
    step2Title: 'సమయం & చిరునామా నిర్ణయించండి',
    step2Desc: 'మీ అనుకూల సమయాన్ని ఎంచుకోండి. సమీపంలోని సహకార కార్మికుడు కేటాయించబడతారు.',
    step3Title: 'సురక్షితమైన పని & ప్రభుత్వ బిల్లు',
    step3Desc: 'కార్మికుడు ఐడీ కార్డు & ఓటీపీ ధృవీకరణతో వస్తారు. పని ముగిసిన తర్వాత ఫారం IV బిల్లు పొందండి.',

    // Stats Section
    welfareHeading: 'ప్రతి కార్మికుడికి 100% సామాజిక భద్రత',
    welfareSub: 'ప్రతి బుకింగ్ నమోదిత సహకార కార్మికుల ఆరోగ్య బీమా మరియు పెన్షన్‌కు మద్దతు ఇస్తుంది.',
    statVerifiedWorkers: 'ధృవీకరించబడిన కార్మికులు',
    statCooperatives: 'సక్రియ ఫెడరేషన్లు',
    statJobsCompleted: 'పూర్తయిన పనులు',
    statSatisfaction: 'సంతృప్తి రేటు',

    // Worker Onboarding Banner
    workerCampaignBadge: '👷 నైపుణ్యం కలిగిన కార్మికుల నమోదు ప్రచారం',
    workerCampaignTitle: 'మీరు నైపుణ్యం కలిగిన కార్మికులా? ఈరోజే చేరండి!',
    workerCampaignDesc: 'మీ స్థానిక సహకార సంఘంలో చేరండి మరియు 0% కమీషన్, 100% ఆరోగ్య బీమా మరియు గౌరవప్రదమైన ఆదాయాన్ని పొందండి.',
    workerJoinBtn: 'కార్మికుడిగా నమోదు చేసుకోండి →',

    // Navigation Links
    navHome: 'హోమ్',
    navServices: 'సేవలు',
    navFindWorker: 'కార్మికుడిని కనుగొనండి',
    navBookService: 'సేవను బుక్ చేయండి',
    navAbout: 'మా గురించి',
    navHelp: 'సహాయం',

    // Common Buttons
    btnCancel: 'రద్దు చేయండి',
    btnPrintBill: 'ఫారం IV బిల్లును ప్రింట్ చేయండి',
    btnViewTimeline: 'పురోగతిని చూడండి',
    btnPay: 'చెల్లించండి',
    btnSubmit: 'సమర్పించండి',

    findWorkerBadge: 'ధృవీకరించబడిన సహకార కార్మికుల డైరెక్టరీ',
    findWorkerTitle: 'ధృవీకరించబడిన సహకార కార్మికులను కనుగొనండి',
    findWorkerSub: 'అన్ని జిల్లాల్లో నమోదిత లేబర్ సహకార ఫెడరేషన్ల నుండి ధృవీకరించబడిన వృత్తి నిపుణులను కనుగొనండి.',
    voiceSearchTitle: 'మాట్లాడి శోధించండి',
    tradeLabel: 'వృత్తి',
    districtLabel: 'జిల్లా',
    statusLabel: 'స్థితి',
    allTrades: 'అన్ని వృత్తులు',
    allDistricts: 'అన్ని జిల్లాలు',
    anyStatus: 'ఏదైనా స్థితి',
    statusAvailable: 'అందుబాటులో ఉంది',
    statusBusy: 'బిజీ',
    statusOffline: 'ఆఫ్‌లైన్',
    verifiedOnly: 'ధృవీకరించబడినవి మాత్రమే',
    resetFilters: 'అన్ని ఫిల్టర్లను రీసెట్ చేయండి',
    verified: 'ధృవీకరించబడింది',
    pending: 'పెండింగ్',
    viewProfile: 'వివరాలు చూడండి',
    noWorkersFound: 'మీ శోధనలో ఎటువంటి కార్మికులు కనుగొనబడలేదు.',
    loadingWorkers: 'ధృవీకరించబడిన సహకార కార్మికులు లోడ్ అవుతున్నారు...',
    bookThisArtisan: 'ఈ కార్మికుడిని బుక్ చేయండి',
    coopAffiliation: 'సహకార అనుబంధం',
    primaryTrade: 'ప్రధాన వృత్తి',
    experience: 'అనుభవం',
    rating: 'రేటింగ్',
    completed: 'పూర్తి',
    years: 'సంవత్సరాలు',
    artisanBio: 'కార్మిక పరిచయం',
    close: 'మూసివేయండి',

    servicesDirectoryBadge: 'ప్రామాణిక ప్రభుత్వ సేవా ధరల డైరెక్టరీ',
    zeroSurgeBannerTitle: 'అదనపు ధర లేదు - హామీ',
    zeroSurgeBannerDesc: 'అన్ని ధరలు రాష్ట్ర సహకార సంఘం ద్వారా ప్రామాణీకరించబడ్డాయి. దాచిన ఛార్జీలు లేవు.',
    tollFreeBookingLabel: 'టోల్-ఫ్రీ ఫోన్ బుకింగ్',
    searchServicesPlaceholder: 'సేవలను శోధించండి (ఉదా., విద్యుత్ మరమ్మతు, లీకేజ్, శుభ్రపరచడం)...',
    categoryLabel: 'వర్గం',
    allCategories: 'అన్ని సేవలు',
    clearFilters: 'ఫిల్టర్లను క్లియర్ చేయండి',
    loadingServices: 'సహకార సేవల డైరెక్టరీ లోడ్ అవుతోంది...',
    noServicesFound: 'మీ శోధనలో ఎటువంటి సేవలు కనుగొనబడలేదు.',
    viewWorkers: 'కార్మికులను చూడండి',
    verifiedWorkerCount: 'ధృవీకరించబడిన కార్మికులు',
    coopBaseRate: 'సహకార బేస్ రేటు',
    priorityEmergency: '24/7 అత్యవసర సేవ',
    responseTime: '30 నిమిషాల్లో స్పందన',

    myBookingsTitle: 'నా సేవా బుకింగ్‌లు',
    myBookingsSub: 'మీ గృహ సేవా ఆర్డర్లను ట్రాక్ మరియు నిర్వహించండి',
    bookNewService: 'కొత్త సేవను బుక్ చేయండి',
    tabAll: 'అన్నీ',
    tabActive: 'సక్రియ',
    tabCompleted: 'పూర్తి',
    tabCancelled: 'రద్దు',
    statusRequested: 'అభ్యర్థన స్వీకరించబడింది',
    statusMatched: 'కార్మికుడు కేటాయించబడ్డారు',
    statusAccepted: 'ఆమోదించబడింది',
    statusInProgress: 'పని జరుగుతోంది',
    statusCompleted: 'విజయవంతంగా పూర్తయింది',
    statusCancelled: 'రద్దు చేయబడింది',
    confirmCancel: 'మీరు ఈ బుకింగ్‌ను రద్దు చేయాలనుకుంటున్నారా?',
    noBookings: 'బుకింగ్‌లు కనుగొనబడలేదు.',
    bookFirstService: 'ప్రారంభించడానికి మీ మొదటి సేవను బుక్ చేయండి.',
    warrantyBadge: '7-రోజుల ఉచిత మరమ్మతు హామీ',
    warrantySub: 'పనిలో లోపం ఉంటే 7 రోజుల్లో మాస్టర్ కార్మికుడి ద్వారా ₹0 ఖర్చుతో పరిష్కారం.',

    catElectrical: 'విద్యుత్',
    catPlumbing: 'ప్లంబింగ్',
    catCarpentry: 'వడ్రంగి',
    catPainting: 'రంగులు',
    catCleaning: 'శుభ్రపరచడం',
    catGardening: 'తోటపని',
    catCaregiving: 'సంరక్షణ',
    catDriving: 'డ్రైవింగ్',
    catAppliance: 'ఉపకరణ మరమ్మతు',
    catDomestic: 'గృహ సేవ',
    catTechnician: 'IT / టెక్నీషియన్',
    searchBtn: 'శోధించండి',
    resetAllFilters: 'అన్ని ఫిల్టర్లను రీసెట్ చేయండి',

    problemSearchTitle: 'సమస్య శోధన & ప్రభుత్వ ధరల పట్టిక',
    problemSearchSub: 'మీ మరమ్మతు సమస్యను వివరించండి లేదా దిగువ ఎంపికలను ఎంచుకోండి',
    problemSearchDesc: 'మా పోర్టల్ మీ అవసరాన్ని తక్షణమే ధృవీకరించబడిన ప్రభుత్వ ధరలతో కలుపుతుంది.',
    searchIssuePlaceholder: 'సమస్యను టైప్ చేయండి (ఉదా. కుళాయి లీక్, ఫ్యాన్ పని చేయకపోవడం, ఏసీ గ్యాస్)...',
    btnFindServiceRate: 'సేవ & ధరను కనుగొనండి',
    matchedService: 'సరిపోలిన సేవ',
    govStandardRate: 'ప్రభుత్వ నియంత్రిత ధర',
    orSelectManual: 'లేదా అన్ని ప్రామాణిక ప్రజా సేవల నుండి ఎంచుకోండి',
    matchingServicesFound: 'సరిపోలే సేవలు కనుగొనబడ్డాయి',
    clearSearch: 'శోధనను క్లియర్ చేయండి',
    btnContinueQuote: 'ఎంచుకున్న సేవతో కొనసాగించండి',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('gov_language') || 'EN';
  });

  const setLang = (newLang) => {
    localStorage.setItem('gov_language', newLang);
    setLangState(newLang);
  };

  const t = (key) => {
    const currentDict = TRANSLATIONS[lang] || TRANSLATIONS.EN;
    return currentDict[key] || TRANSLATIONS.EN[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
