import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../storage/storage_service.dart';
import '../network/api_client.dart';
import '../constants/api_endpoints.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLocale = 'EN';
  Map<String, dynamic> _remoteDict = {};

  String get currentLocale => _currentLocale;

  Locale get currentFlutterLocale {
    switch (_currentLocale) {
      case 'HI':
        return const Locale('hi', 'IN');
      case 'OR':
        return const Locale('or', 'IN');
      case 'BN':
        return const Locale('bn', 'IN');
      case 'TE':
        return const Locale('te', 'IN');
      case 'EN':
      default:
        return const Locale('en', 'US');
    }
  }

  final Map<String, String> supportedLanguages = {
    'EN': 'English',
    'OR': 'ଓଡ଼ିଆ (Odia)',
    'HI': 'हिंदी (Hindi)',
    'BN': 'বাংলা (Bengali)',
    'TE': 'తెలుగు (Telugu)',
  };

  LanguageProvider() {
    _currentLocale = StorageService.getLanguage();
    fetchRemoteTranslations(_currentLocale);
  }

  Future<void> setLanguage(String langCode) async {
    if (!supportedLanguages.containsKey(langCode)) return;
    _currentLocale = langCode;
    await StorageService.saveLanguage(langCode);
    notifyListeners();
    await fetchRemoteTranslations(langCode);
  }

  Future<void> fetchRemoteTranslations(String langCode) async {
    try {
      final res = await ApiClient().get(ApiEndpoints.localizationDict(langCode));
      if (res is Map && res['dictionary'] is Map) {
        _remoteDict = Map<String, dynamic>.from(res['dictionary']);
        notifyListeners();
      }
    } catch (_) {
      // Fallback to local static dictionary if network fails
    }
  }

  String translate(String key) {
    if (_remoteDict.containsKey(key) && _remoteDict[key] is String) {
      return _remoteDict[key];
    }
    return _localDictionaries[_currentLocale]?[key] ??
        _localDictionaries['EN']?[key] ??
        key;
  }

  static final Map<String, Map<String, String>> _localDictionaries = {
    'EN': {
      'app_title': 'Prithvi Fix',
      'app_subtitle': 'Cooperative Gig Services Platform',
      'tagline': 'Verified Skills. Fair Work. Stronger Communities.',
      'odisha_network': 'ODISHA COOPERATIVE NETWORK',
      'home': 'Home',
      'services': 'Services',
      'find_worker': 'Find Worker',
      'bookings': 'Bookings',
      'rate_card': 'Rate Card',
      'about': 'About Us',
      'help': 'Help & Support',
      'login': 'Login',
      'register': 'Register',
      'logout': 'Logout',
      'welfare': 'Social Welfare',
      'admin': 'Federation Admin',
      'societies': 'Societies',
      'tenders': 'Institutional Tenders',
      'emergency_toggle': '24/7 Priority Emergency',
      'emergency_desc': 'Dispatched within 15 minutes by on-duty emergency squad',
      'escrow_model': '93-2-5 Cooperative Escrow Model',
      'escrow_desc': '93% direct worker living wage, 5% PF & insurance safety net, 2% platform upkeep.',
      'customer': 'Citizen / Customer',
      'worker': 'Skilled Artisan / Worker',
      'admin_role': 'Federation Administrator',
      'treasurer': 'Federation Treasurer',
      'book_now': 'Book Service',
      'book_service_btn': 'Book Service',
      'rate_card_btn': 'Rate Card',
      'view_details': 'View Details',
      'verified_artisan': 'State Skill Verified',
      'arrival_otp': 'Arrival OTP',
      'completion_otp': 'Completion OTP',
      'pay_now': 'Pay ₹',
      'tax_invoice': 'Form IV Tax Invoice',
      'download_invoice': 'Download Tax Invoice',
      'claim_guarantee': '30-Day Guarantee',
      'leave_review': 'Leave Review',
      'status_requested': 'Requested',
      'status_matched': 'Matched',
      'status_accepted': 'Accepted',
      'status_in_progress': 'In Progress',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      'duty_available': 'AVAILABLE NOW',
      'duty_busy': 'ON JOB / BUSY',
      'duty_offline': 'OFFLINE',
      'zero_surge': '₹0 Surge Pricing',
      'iti_certified': 'Skill Certified',
      'warranty_30d': '30-Day Warranty',
      'worker_take_home': 'Artisan Wage (93%)',
      'welfare_fund': 'Welfare & ESIC (5%)',
      'platform_fee': 'Platform Upkeep (2%)',
      'press_back_again': 'Press back again to exit Prithvi Fix',
      'select_language': 'Language / ଭାଷା',
      'guest_monitor_mode': 'Guest Monitor Mode',
      'guest_signin_prompt': 'Sign-in required to book services',
      'signin_title': 'Portal Sign-In',
      'signin_welcome': 'Welcome to Prithvi Fix',
      'signin_citizen_desc': 'Sign in to book certified artisans, track repairs, and receive statutory invoices.',
      'signin_artisan_desc': 'Sign in to manage assigned jobs, verify completion OTPs, and access welfare funds.',
      'signin_admin_desc': 'Sign in to oversee district federations, tenders, and cooperative compliance.',
      'citizen_tab': 'Citizen',
      'artisan_tab': 'Artisan',
      'admin_tab': 'Admin',
      'email_label': 'Registered Email Address',
      'password_label': 'Password',
      'signin_button': 'Sign In to Account',
      'signing_in': 'Signing In...',
      'dont_have_account': "Don't have an account?",
      'register_now': 'Create Account',
      'explore_as_guest': 'Explore as Guest (Monitor Only)',
      'welcome_title': 'Verified Skills. Fair Work.',
      'welcome_subtitle': 'Odisha\'s state-regulated labour cooperative network.',
      'settings': 'Settings & Preferences',
      // Parity & Location additions
      'select_location': 'Select Cooperative Area',
      'detect_location': 'Use Current Location (GPS)',
      'detecting_gps': 'Detecting GPS...',
      'coming_soon_banner': 'Expansion Notice: Coming Soon',
      'coming_soon_title': 'Services Coming Soon to',
      'coming_soon_sub': 'Prithvi Fix cooperative services are actively serving Khordha, Cuttack, and Puri. Phase 2 expansion is launching here shortly.',
      'browse_bhubaneswar': 'Browse Active Bhubaneswar Hub',
      'search_services_hint': 'Search electrician, plumber, carpenter...',
      'trust_zero_brokerage': '₹0 Brokerage',
      'trust_zero_brokerage_desc': 'Direct cooperative booking',
      'trust_93_worker': '93% to Artisan',
      'trust_93_worker_desc': 'Fair living wage escrow',
      'trust_police_verified': '100% Verified',
      'trust_police_verified_desc': 'Aadhaar & Police audited',
      'trust_45min_sla': '45-Min Response',
      'trust_45min_sla_desc': 'Cooperative duty squads',
      'rate_calc_title': 'Transparent 93-2-5 Price Engine',
      'rate_calc_desc': 'Slide or enter job budget to see exact statutory wage breakdown with zero hidden cuts.',
      'popular_trades': 'Verified Cooperative Trades',
      'view_all_trades': 'View All Services',
      'authentic_reviews': 'Citizen Testimonials',
      'authentic_reviews_sub': 'Real verified service reviews from across Odisha',
    },
    'OR': {
      'app_title': 'ପୃଥିବୀ ଫିକ୍ସ',
      'app_subtitle': 'ସରକାରୀ ଶ୍ରମ ସମବାୟ ସେବା ପୋର୍ଟାଲ',
      'tagline': 'ଯାଞ୍ଚ ହୋଇଥିବା ଦକ୍ଷତା। ନ୍ୟାଯ୍ୟ କାର୍ଯ୍ୟ। ସଶକ୍ତ ସମୁଦାୟ।',
      'odisha_network': 'ଓଡ଼ିଶା ସମବାୟ ନେଟୱାର୍କ',
      'home': 'ମୂଳପୃଷ୍ଠା',
      'services': 'ସେବାସମୂହ',
      'find_worker': 'କୁଶଳୀ କାରିଗର',
      'bookings': 'ମୋର ବୁକିଂ',
      'rate_card': 'ଦର ତାଲିକା',
      'about': 'ଆମ ବିଷୟରେ',
      'help': 'ସହାୟତା',
      'login': 'ଲଗଇନ୍',
      'register': 'ପଞ୍ଜୀକରଣ',
      'logout': 'ଲଗ୍ ଆଉଟ୍',
      'welfare': 'ଶ୍ରମିକ କଲ୍ୟାଣ ପାଣ୍ଠି',
      'admin': 'ଫେଡେରେସନ ପ୍ରଶାସନ',
      'societies': 'ସମବାୟ ସମିତି',
      'tenders': 'ସରକାରୀ ଟେଣ୍ଡର',
      'emergency_toggle': '୨୪/୭ ଜରୁରୀକାଳୀନ ସେବା',
      'emergency_desc': '୧୫ ମିନିଟ୍ ମଧ୍ୟରେ ଅନ-ଡ୍ୟୁଟି ଦଳ ଦ୍ୱାରା ତ୍ୱରିତ ସେବା',
      'escrow_model': '୯୩-୨-୫ ସମବାୟ ଏସ୍କ୍ରୋ ମଡେଲ',
      'escrow_desc': '୯୩% ସିଧାସଳଖ ଶ୍ରମିକ ମଜୁରୀ, ୫% ପିଏଫ ଓ ବୀମା କଲ୍ୟାଣ, ୨% ପୋର୍ଟାଲ ପରିଚାଳନା।',
      'customer': 'ନାଗରିକ / ଗ୍ରାହକ',
      'worker': 'କୁଶଳୀ ଶ୍ରମିକ / କାରିଗର',
      'admin_role': 'ଫେଡେରେସନ ସମ୍ପାଦକ',
      'treasurer': 'ଫେଡେରେସନ କୋଷାଧ୍ୟକ୍ଷ',
      'book_now': 'ସେବା ବୁକ୍ କରନ୍ତୁ',
      'book_service_btn': 'ସେବା ବୁକ୍ କରନ୍ତୁ',
      'rate_card_btn': 'ଦର ତାଲିକା',
      'view_details': 'ବିବରଣୀ ଦେଖନ୍ତୁ',
      'verified_artisan': 'ସରକାରୀ ଆଇଟିଆଇ ଯାଞ୍ଚପ୍ରାପ୍ତ',
      'arrival_otp': 'ପହଞ୍ଚିବା ଓଟିପି',
      'completion_otp': 'ସମାପ୍ତ ଓଟିପି',
      'pay_now': 'ପୈଠ କରନ୍ତୁ ₹',
      'tax_invoice': 'ଫର୍ମ IV ଟ୍ୟାକ୍ସ ଇନଭଏସ',
      'download_invoice': 'ଇନଭଏସ ଡାଉନଲୋଡ୍',
      'claim_guarantee': '୩୦-ଦିନ କାର୍ଯ୍ୟ ଗ୍ୟାରେଣ୍ଟି',
      'leave_review': 'ମତାମତ ଦିଅନ୍ତୁ',
      'status_requested': 'ଅନୁରୋଧିତ',
      'status_matched': 'ମିଳିତ',
      'status_accepted': 'ଗ୍ରହଣ କରାଯାଇଛି',
      'status_in_progress': 'ଚାଲୁ ରହିଛି',
      'status_completed': 'ସମ୍ପନ୍ନ',
      'status_cancelled': 'ବାତିଲ୍',
      'duty_available': 'ଡ୍ୟୁଟି ଉପଲବ୍ଧ',
      'duty_busy': 'କାର୍ଯ୍ୟବ୍ୟସ୍ତ',
      'duty_offline': 'ଅଫଲାଇନ୍',
      'zero_surge': '₹୦ ସର୍ଜ ଶୁଳ୍କ',
      'iti_certified': 'ଆଇଟିଆଇ ପ୍ରମାଣିତ',
      'warranty_30d': '୩୦-ଦିନ ଗ୍ୟାରେଣ୍ଟି',
      'worker_take_home': 'ଶ୍ରମିକ ମଜୁରୀ (୯୩%)',
      'welfare_fund': 'କଲ୍ୟାଣ ଓ ଇଏସଆଇସି (୫%)',
      'platform_fee': 'ପୋର୍ଟାଲ ପରିଚାଳନା (୨%)',
      'press_back_again': 'ପ୍ରସ୍ଥାନ କରିବାକୁ ପୁନର୍ବାର ବ୍ୟାକ୍ ଦବାନ୍ତୁ',
      'select_language': 'ଭାଷା ବାଛନ୍ତୁ',
      'guest_monitor_mode': 'ଅତିଥି ନିରୀକ୍ଷଣ ମୋଡ୍',
      'guest_signin_prompt': 'ସେବା ବୁକ୍ କରିବା ପାଇଁ ସାଇନ୍-ଇନ୍ ଆବଶ୍ୟକ',
      'signin_title': 'ପୋର୍ଟାଲ୍ ସାଇନ୍-ଇନ୍',
      'signin_welcome': 'ପୃଥିବୀ ଫିକ୍ସକୁ ସ୍ୱାଗତ',
      'signin_citizen_desc': 'ସରକାରୀ ଯାଞ୍ଚପ୍ରାପ୍ତ କାରିଗର ସେବା ବୁକ୍ କରିବା ଓ ଟ୍ୟାକ୍ସ ଇନଭଏସ ପାଇଁ ସାଇନ୍-ଇନ୍ କରନ୍ତୁ।',
      'signin_artisan_desc': 'ଦୈନିକ କାର୍ଯ୍ୟ, ଓଟିପି ଯାଞ୍ଚ ଓ ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଜମା ଦେଖିବାକୁ ସାଇନ୍-ଇନ୍ କରନ୍ତୁ।',
      'signin_admin_desc': 'ଜିଲ୍ଲା ସମବାୟ ଫେଡେରେସନ, ଟେଣ୍ଡର ଓ ନିୟମାବଳୀ ପରିଚାଳନା ପାଇଁ ସାଇନ୍-ଇନ୍ କରନ୍ତୁ।',
      'citizen_tab': 'ନାଗରିକ',
      'artisan_tab': 'କାରିଗର',
      'admin_tab': 'ପ୍ରଶାସକ',
      'email_label': 'ପଞ୍ଜୀକୃତ ଇମେଲ୍ ଠିକଣା',
      'password_label': 'ପାସୱାର୍ଡ',
      'signin_button': 'ଖାତାରେ ସାଇନ୍-ଇନ୍ କରନ୍ତୁ',
      'signing_in': 'ସାଇନ୍-ଇନ୍ ହେଉଛି...',
      'dont_have_account': 'ଖାତା ନାହିଁ କି?',
      'register_now': 'ନୂଆ ଖାତା ଖୋଲନ୍ତୁ',
      'explore_as_guest': 'ଅତିଥି ଭାବରେ ଦେଖନ୍ତୁ (କେବଳ ନିରୀକ୍ଷଣ)',
      'welcome_title': 'ଯାଞ୍ଚ ହୋଇଥିବା ଦକ୍ଷତା। ନ୍ୟାଯ୍ୟ କାର୍ଯ୍ୟ।',
      'welcome_subtitle': 'ଓଡ଼ିଶାର ପଞ୍ଜୀକୃତ ଜିଲ୍ଲା ଶ୍ରମ ସମବାୟ ଫେଡେରେସନ ନେଟୱାର୍କ।',
      'settings': 'ସେଟିଙ୍ଗ୍ ଓ ପସନ୍ଦ',
      'select_location': 'ସମବାୟ ଅଞ୍ଚଳ ବାଛନ୍ତୁ',
      'detect_location': 'ବର୍ତ୍ତମାନର ସ୍ଥାନ (GPS)',
      'detecting_gps': 'ଜିପିଏସ୍ ଯାଞ୍ଚ ହେଉଛି...',
      'coming_soon_banner': 'ସେବା ବିସ୍ତାର: ଖୁବ୍ ଶୀଘ୍ର ଆସୁଛି',
      'coming_soon_title': 'ସେବା ଖୁବ୍ ଶୀଘ୍ର ଉପଲବ୍ଧ ହେବ',
      'coming_soon_sub': 'ପୃଥିବୀ ଫିକ୍ସ ବର୍ତ୍ତମାନ ଖୋର୍ଦ୍ଧା, କଟକ ଓ ପୁରୀ ଜିଲ୍ଲାରେ ସକ୍ରିୟ। ଆପଣଙ୍କ ଅଞ୍ଚଳରେ ଦ୍ୱିତୀୟ ପର୍ଯ୍ୟାୟରେ ଖୁବ୍ ଶୀଘ୍ର ଉପଲବ୍ଧ ହେବ।',
      'browse_bhubaneswar': 'ଭୁବନେଶ୍ୱର ହବ୍ ସେବା ଦେଖନ୍ତୁ',
      'search_services_hint': 'ଇଲେକ୍ଟ୍ରିସିଆନ୍, ପ୍ଲମ୍ବର, ବଢ଼େଇ ଖୋଜନ୍ତୁ...',
      'trust_zero_brokerage': '₹୦ ଦଲାଲି ଶୁଳ୍କ',
      'trust_zero_brokerage_desc': 'ସିଧାସଳଖ ସମବାୟ ବୁକିଂ',
      'trust_93_worker': '୯୩% ଶ୍ରମିକଙ୍କୁ',
      'trust_93_worker_desc': 'ନ୍ୟାଯ୍ୟ ମଜୁରୀ ଏସ୍କ୍ରୋ',
      'trust_police_verified': '୧୦୦% ଯାଞ୍ଚପ୍ରାପ୍ତ',
      'trust_police_verified_desc': 'ଆଧାର ଓ ପୋଲିସ ଯାଞ୍ଚ',
      'trust_45min_sla': '୪୫ ମିନିଟ୍ ରେସପନ୍ସ',
      'trust_45min_sla_desc': 'ଅନ-ଡ୍ୟୁଟି ସମବାୟ ଦଳ',
      'rate_calc_title': '୯୩-୨-୫ ସ୍ୱଚ୍ଛ ଦର କାଲକୁଲେଟର',
      'rate_calc_desc': 'ବଜେଟ୍ ସ୍ଲାଇଡର୍ ବ୍ୟବହାର କରି କାରିଗର ପାଉଣା ଓ ସରକାରୀ ବିଭାଜନ ଯାଞ୍ଚ କରନ୍ତୁ।',
      'popular_trades': 'ପ୍ରମାଣିତ ସମବାୟ ସେବା',
      'view_all_trades': 'ସମସ୍ତ ସେବା ଦେଖନ୍ତୁ',
      'authentic_reviews': 'ନାଗରିକ ପ୍ରତିକ୍ରିୟା',
      'authentic_reviews_sub': 'ଓଡ଼ିଶାର ଗ୍ରାହକମାନଙ୍କ ପ୍ରମାଣିତ ମତାମତ',
    },
    'HI': {
      'app_title': 'पृथ्वी फिक्स',
      'app_subtitle': 'सहकारी गिग सेवा मंच',
      'tagline': 'प्रमाणित कौशल। निष्पक्ष काम। सशक्त समुदाय।',
      'odisha_network': 'ओडिशा सहकारी नेटवर्क',
      'home': 'होम',
      'services': 'सेवाएं',
      'find_worker': 'कारीगर खोजें',
      'bookings': 'मेरी बुकिंग्स',
      'rate_card': 'दर सूची',
      'about': 'हमारे बारे में',
      'help': 'सहायता केंद्र',
      'login': 'लॉग इन',
      'register': 'पंजीकरण',
      'logout': 'लॉग आउट',
      'welfare': 'श्रमिक कल्याण केंद्र',
      'admin': 'फेडरेशन प्रशासन',
      'societies': 'समितियां',
      'tenders': 'संस्थागत निविदाएं',
      'emergency_toggle': '24/7 आपातकालीन सेवा',
      'emergency_desc': '15 मिनट के भीतर आपातकालीन दस्ते द्वारा त्वरित सेवा',
      'escrow_model': '93-2-5 सहकारी एस्क्रो मॉडल',
      'escrow_desc': '93% सीधे कारीगर की आजीविका, 5% पीएफ एवं सुरक्षा कवच, 2% मंच रखरखाव।',
      'customer': 'नागरिक / उपभोक्ता',
      'worker': 'कुशल कारीगर / श्रमिक',
      'admin_role': 'फेडरेशन प्रशासक',
      'treasurer': 'फेडरेशन कोषाध्यक्ष',
      'book_now': 'सेवा बुक करें',
      'book_service_btn': 'सेवा बुक करें',
      'rate_card_btn': 'दर सूची',
      'view_details': 'विवरण देखें',
      'verified_artisan': 'आईटीआई सत्यापित',
      'arrival_otp': 'आगमन ओटीपी',
      'completion_otp': 'समापन ओटीपी',
      'pay_now': 'भुगतान करें ₹',
      'tax_invoice': 'फॉर्म IV कर चालान',
      'download_invoice': 'चालान डाउनलोड करें',
      'claim_guarantee': '30-दिन कारीगरी गारंटी',
      'leave_review': 'समीक्षा दर्ज करें',
      'status_requested': 'अनुरोधित',
      'status_matched': 'सुझाया गया',
      'status_accepted': 'स्वीकृत',
      'status_in_progress': 'प्रगति पर',
      'status_completed': 'पूर्ण',
      'status_cancelled': 'रद्द',
      'duty_available': 'ड्यूटी पर उपलब्ध',
      'duty_busy': 'काम पर / व्यस्त',
      'duty_offline': 'ऑफलाइन',
      'zero_surge': '₹0 सर्ज शुल्क',
      'iti_certified': 'आईटीआई प्रमाणित',
      'warranty_30d': '30-दिन वारंटी',
      'worker_take_home': 'कारीगर पारिश्रमिक (93%)',
      'welfare_fund': 'कल्याण एवं ईएसआईसी (5%)',
      'platform_fee': 'मंच रख-रखाव (2%)',
      'press_back_again': 'बाहर निकलने के लिए पुनः बैक दबाएं',
      'select_language': 'भाषा चुनें',
      'guest_monitor_mode': 'अतिथि मॉनिटर मोड',
      'guest_signin_prompt': 'सेवा बुक करने हेतु साइन-इन आवश्यक',
      'signin_title': 'पोर्टल साइन-इन',
      'signin_welcome': 'पृथ्वी फिक्स में आपका स्वागत है',
      'signin_citizen_desc': 'प्रमाणित कारीगर सेवाएं बुक करने और कर चालान प्राप्त करने के लिए साइन इन करें।',
      'signin_artisan_desc': 'दैनिक कार्य, ओटीपी सत्यापन और सीधे बैंक भुगतान देखने के लिए साइन इन करें।',
      'signin_admin_desc': 'जिला फेडरेशन, निविदाएं और सहकारी नियमों के प्रबंधन हेतु साइन इन करें।',
      'citizen_tab': 'नागरिक',
      'artisan_tab': 'कारीगर',
      'admin_tab': 'प्रशासक',
      'email_label': 'पंजीकृत ईमेल पता',
      'password_label': 'पासवर्ड',
      'signin_button': 'खाते में साइन इन करें',
      'signing_in': 'साइन इन हो रहा है...',
      'dont_have_account': 'खाता नहीं है?',
      'register_now': 'नया खाता बनाएं',
      'explore_as_guest': 'अतिथि के रूप में देखें (केवल मॉनिटर)',
      'welcome_title': 'प्रमाणित कौशल। निष्पक्ष काम।',
      'welcome_subtitle': 'ओडिशा का राज्य-पंजीकृत श्रम सहकारी नेटवर्क।',
      'settings': 'सेटिंग्स एवं प्राथमिकताएं',
      'select_location': 'सहकारी क्षेत्र चुनें',
      'detect_location': 'वर्तमान स्थान (GPS)',
      'detecting_gps': 'जीपीएस खोजा जा रहा है...',
      'coming_soon_banner': 'विस्तार सूचना: शीघ्र आ रहा है',
      'coming_soon_title': 'सेवाएं जल्द ही आ रही हैं',
      'coming_soon_sub': 'पृथ्वी फिक्स सेवाएं वर्तमान में खोर्धा, कटक और पुरी में सक्रिय हैं। आपके क्षेत्र में द्वितीय चरण जल्द शुरू होगा।',
      'browse_bhubaneswar': 'सक्रिय भुवनेश्वर हब देखें',
      'search_services_hint': 'इलेक्ट्रीशियन, प्लंबर, बढ़ई खोजें...',
      'trust_zero_brokerage': '₹0 बिचौलिया शुल्क',
      'trust_zero_brokerage_desc': 'सीधी सहकारी बुकिंग',
      'trust_93_worker': '93% कारीगर को',
      'trust_93_worker_desc': 'पारदर्शी एस्क्रो व्यवस्था',
      'trust_police_verified': '100% सत्यापित',
      'trust_police_verified_desc': 'आधार व पुलिस रिकॉर्ड ऑडिट',
      'trust_45min_sla': '45-मिनट रिस्पांस',
      'trust_45min_sla_desc': 'ऑन-ड्यूटी सहकारी दल',
      'rate_calc_title': '93-2-5 पारदर्शी दर कैलकुलेटर',
      'rate_calc_desc': 'बजट स्लाइडर से कारीगर पारिश्रमिक और वैधानिक बंटवारे की सटीक जानकारी पाएं।',
      'popular_trades': 'प्रमाणित सहकारी सेवाएं',
      'view_all_trades': 'सभी सेवाएं देखें',
      'authentic_reviews': 'नागरिक समीक्षाएं',
      'authentic_reviews_sub': 'ओडिशा के नागरिकों द्वारा सत्यापित अनुभव',
    },
    'BN': {
      'app_title': 'পৃথ্বী ফিক্স',
      'app_subtitle': 'সমবায় গিগ সেবা প্ল্যাটফর্ম',
      'tagline': 'যাচাইকৃত দক্ষতা। ন্যায্য কাজ। শক্তিশালী সম্প্রদায়।',
      'odisha_network': 'ওড়িশা সমবায় নেটওয়ার্ক',
      'home': 'হোম',
      'services': 'সেবাসমূহ',
      'find_worker': 'কারিগর খুঁজুন',
      'bookings': 'আমার বুকিং',
      'rate_card': 'দর তালিকা',
      'about': 'আমাদের কথা',
      'help': 'সহায়তা কেন্দ্র',
      'login': 'লগইন',
      'register': 'নিবন্ধন',
      'logout': 'লগআউট',
      'welfare': 'শ্রমিক কল্যাণ তহবিল',
      'admin': 'ফেডারেশন প্রশাসন',
      'societies': 'সমিতি সমূহ',
      'tenders': 'প্রাতিষ্ঠানিক টেন্ডার',
      'emergency_toggle': '২৪/৭ জরুরি পরিষেবা',
      'emergency_desc': 'অন-ডিউটি স্কোয়াড দ্বারা ১৫ মিনিটের মধ্যে দ্রুত পরিষেবা',
      'escrow_model': '৯৩-২-৫ সমবায় এসক্রো মডেল',
      'escrow_desc': '৯৩% সরাসরি কারিগরের মজুরি, ৫% পিএফ ও স্বাস্থ্য নিরাপত্তা, ২% প্ল্যাটফর্ম রক্ষণাবেক্ষণ।',
      'customer': 'নাগরিক / গ্রাহক',
      'worker': 'দক্ষ কারিগর / শ্রমিক',
      'admin_role': 'ফেডারেশন প্রশাসক',
      'treasurer': 'ফেডারেশন কোষাধ্যক্ষ',
      'book_now': 'সেবা বুক করুন',
      'book_service_btn': 'সেবা বুক করুন',
      'rate_card_btn': 'দর তালিকা',
      'view_details': 'বিস্তারিত দেখুন',
      'verified_artisan': 'আইটিআই প্রত্যয়িত',
      'arrival_otp': 'আগমনের ওটিপি',
      'completion_otp': 'সমাপ্তির ওটিপি',
      'pay_now': 'পরিশোধ করুন ₹',
      'tax_invoice': 'ফর্ম IV ট্যাক্স চালান',
      'download_invoice': 'চালান ডাউনলোড করুন',
      'claim_guarantee': '৩০ দিনের কাজের গ্যারান্টি',
      'leave_review': 'মতামত দিন',
      'status_requested': 'অনুরোধ করা হয়েছে',
      'status_matched': 'পাওয়া গেছে',
      'status_accepted': 'গৃহীত',
      'status_in_progress': 'চলমান',
      'status_completed': 'সম্পন্ন',
      'status_cancelled': 'বাতিল',
      'duty_available': 'ডিউটিতে উপলব্ধ',
      'duty_busy': 'কাজে ব্যস্ত',
      'duty_offline': 'অফলাইন',
      'zero_surge': '₹০ সার্জ চার্জ',
      'iti_certified': 'আইটিআই প্রত্যয়িত',
      'warranty_30d': '৩০ দিনের ওয়ারেন্টি',
      'worker_take_home': 'কারিগর মজুরি (৯৩%)',
      'welfare_fund': 'কল্যাণ ও ইএসআইসি (৫%)',
      'platform_fee': 'প্ল্যাটফর্ম রক্ষণাবেক্ষণ (২%)',
      'press_back_again': 'প্রস্থান করতে পুনরায় ব্যাক বাটন চাপুন',
      'select_language': 'ভাষা বেছে নিন',
      'guest_monitor_mode': 'অতিথি পর্যবেক্ষণ মোড',
      'guest_signin_prompt': 'বুকিংয়ের জন্য সাইন-ইন আবশ্যক',
      'signin_title': 'পোর্টাল সাইন-ইন',
      'signin_welcome': 'পৃথ্বী ফিক্সে স্বাগতম',
      'signin_citizen_desc': 'প্রত্যয়িত কারিগর বুক করতে ও রসিদ পেতে সাইন ইন করুন।',
      'citizen_tab': 'নাগরিক',
      'artisan_tab': 'কারিগর',
      'admin_tab': 'প্রশাসক',
      'email_label': 'নিবন্ধিত ইমেল',
      'password_label': 'পাসওয়ার্ড',
      'signin_button': 'অ্যাকাউন্টে সাইন ইন করুন',
      'signing_in': 'সাইন ইন হচ্ছে...',
      'dont_have_account': 'অ্যাকাউন্ট নেই?',
      'register_now': 'নতুন অ্যাকাউন্ট খুলুন',
      'explore_as_guest': 'অতিথি হিসেবে দেখুন',
      'welcome_title': 'যাচাইকৃত দক্ষতা। ন্যায্য কাজ।',
      'welcome_subtitle': 'ওড়িশার নিবন্ধিত শ্রম সমবায় ফেডারেশন নেটওয়ার্ক।',
      'settings': 'সেটিংস ও পছন্দ',
      'select_location': 'সমবায় এলাকা নির্বাচন করুন',
      'detect_location': 'বর্তমান অবস্থান (GPS)',
      'detecting_gps': 'জিপিএস খোঁজা হচ্ছে...',
      'coming_soon_banner': 'সম্প্রসারণ বিজ্ঞপ্তি: শীঘ্রই আসছে',
      'coming_soon_title': 'সেবা শীঘ্রই আসছে',
      'coming_soon_sub': 'পৃথ্বী ফিক্স বর্তমানে খুরদা, কটক ও পুরীতে সক্রিয়। আপনার এলাকায় দ্রুত শুরু হচ্ছে।',
      'browse_bhubaneswar': 'ভুবনেশ্বর হাব দেখুন',
      'search_services_hint': 'ইলেকট্রিশিয়ান, প্লাম্বার, ছুতার খুঁজুন...',
      'trust_zero_brokerage': '₹০ দালাল ফি',
      'trust_zero_brokerage_desc': 'সরাসরি সমবায় বুকিং',
      'trust_93_worker': '৯৩% কারিগরকে',
      'trust_93_worker_desc': 'ন্যায্য মজুরি মডেল',
      'trust_police_verified': '১০০% যাচাইকৃত',
      'trust_police_verified_desc': 'আধার ও পুলিশ রেকর্ড চেক',
      'trust_45min_sla': '৪৫ মিনিট দ্রুত সাড়া',
      'trust_45min_sla_desc': 'অন-ডিউটি স্কোয়াড',
      'rate_calc_title': '৯৩-২-৫ স্বচ্ছ মূল্য ক্যালকুলেটর',
      'rate_calc_desc': 'বাজেট স্লাইডারের মাধ্যমে কারিগরের সরাসরি মজুরি দেখুন।',
      'popular_trades': 'জনপ্রিয় সমবায় সেবা',
      'view_all_trades': 'সব সেবা দেখুন',
      'authentic_reviews': 'নাগরিক পর্যালোচনা',
      'authentic_reviews_sub': 'ওড়িশার গ্রাহকদের খাঁটি মতামত',
    },
    'TE': {
      'app_title': 'పృథ్వీ ఫిక్స్',
      'app_subtitle': 'సహకార గిగ్ సేవల వేదిక',
      'tagline': 'ధృవీకరించిన నైపుణ్యం. న్యాయమైన పని. బలమైన సమాజం.',
      'odisha_network': 'ఒడిశా సహకార నెట్‌వర్క్',
      'home': 'హోమ్',
      'services': 'సేవలు',
      'find_worker': 'కార్మికుడిని కనుగొనండి',
      'bookings': 'నా బుకింగ్‌లు',
      'rate_card': 'ధరల పట్టిక',
      'about': 'మా గురించి',
      'help': 'సహాయ కేంద్రం',
      'login': 'లాగిన్',
      'register': 'రిజిస్ట్రేషన్',
      'logout': 'లాగ్ అవుట్',
      'welfare': 'కార్మిక సంక్షేమ నిధి',
      'admin': 'ఫెడరేషన్ అడ్మిన్',
      'societies': 'సొసైటీలు',
      'tenders': 'ప్రభుత్వ టెండర్లు',
      'emergency_toggle': '24/7 అత్యవసర సేవ',
      'emergency_desc': 'ఆన్-డ్యూటీ దళం ద్వారా 15 నిమిషాల్లో వేగవంతమైన సేవ',
      'escrow_model': '93-2-5 సహకార ఎస్క్రో మోడల్',
      'escrow_desc': '93% నేరుగా కార్మికుడి వేతనం, 5% పిఎఫ్ & బీమా, 2% నిర్వహణ రుసుము.',
      'customer': 'పౌరుడు / కస్టమర్',
      'worker': 'నైపుణ్యం కలిగిన కార్మికుడు',
      'admin_role': 'ఫెడరేషన్ అడ్మినిస్ట్రేటర్',
      'treasurer': 'ఫెడరేషన్ కోశాధికారి',
      'book_now': 'సేవ బుక్ చేయండి',
      'book_service_btn': 'సేవ బుక్ చేయండి',
      'rate_card_btn': 'ధరల పట్టిక',
      'view_details': 'వివరాలు చూడండి',
      'verified_artisan': 'ఐటీఐ సర్టిఫైడ్',
      'arrival_otp': 'రాక ఓటీపీ',
      'completion_otp': 'పూర్తి ఓటీపీ',
      'pay_now': 'చెల్లించండి ₹',
      'tax_invoice': 'ఫారం IV పన్ను ఇన్వాయిస్',
      'download_invoice': 'ఇన్వాయిస్ డౌన్‌లోడ్',
      'claim_guarantee': '30 రోజుల వారంటీ',
      'leave_review': 'సమీక్ష ఇవ్వండి',
      'status_requested': 'అభ్యర్థించబడింది',
      'status_matched': 'జతచేయబడింది',
      'status_accepted': 'ఆమోదించబడింది',
      'status_in_progress': 'పురోగతిలో ఉంది',
      'status_completed': 'పూర్తయింది',
      'status_cancelled': 'రద్దు చేయబడింది',
      'duty_available': 'డ్యూటీలో అందుబాటులో ఉన్నారు',
      'duty_busy': 'పనిలో ఉన్నారు',
      'duty_offline': 'ఆఫ్‌లైన్',
      'zero_surge': '₹0 సర్జ్ రుసుము',
      'iti_certified': 'ఐటీఐ ధృవీకృతం',
      'warranty_30d': '30 రోజుల వారంటీ',
      'worker_take_home': 'కార్మికుడి వేతనం (93%)',
      'welfare_fund': 'సంక్షేమం & ఈఎస్ఐసి (5%)',
      'platform_fee': 'ప్లాట్‌ఫారమ్ నిర్వహణ (2%)',
      'press_back_again': 'నిష్క్రమించడానికి మళ్లీ వెనుకకు నొక్కండి',
      'select_language': 'భాషను ఎంచుకోండి',
      'guest_monitor_mode': 'గెస్ట్ మానిటర్ మోడ్',
      'guest_signin_prompt': 'సేవ బుక్ చేయడానికి సైన్ ఇన్ అవసరం',
      'signin_title': 'పోర్టల్ సైన్-ఇన్',
      'signin_welcome': 'పృథ్వీ ఫిక్స్‌కు స్వాగతం',
      'citizen_tab': 'పౌరుడు',
      'artisan_tab': 'కార్మికుడు',
      'admin_tab': 'అడ్మిన్',
      'email_label': 'రిజిస్టర్డ్ ఈమెయిల్',
      'password_label': 'పాస్‌వర్డ్',
      'signin_button': 'ఖాతాలోకి సైన్ ఇన్ అవ్వండి',
      'signing_in': 'సైన్ ఇన్ అవుతోంది...',
      'dont_have_account': 'ఖాతా లేదా?',
      'register_now': 'కొత్త ఖాతా సృష్టించండి',
      'explore_as_guest': 'గెస్ట్‌గా చూడండి',
      'welcome_title': 'ధృవీకరించిన నైపుణ్యం. న్యాయమైన పని.',
      'welcome_subtitle': 'ఒడిశా కార్మిక సహకార ఫెడరేషన్ నెట్‌వర్క్.',
      'settings': 'సెట్టింగ్‌లు & ప్రాధాన్యతలు',
      'select_location': 'సహకార ప్రాంతాన్ని ఎంచుకోండి',
      'detect_location': 'ప్రస్తుత స్థానం (GPS)',
      'detecting_gps': 'జీపీఎస్ గుర్తింపు జరుగుతోంది...',
      'coming_soon_banner': 'విస్తరణ ప్రకటన: త్వరలో ప్రారంభం',
      'coming_soon_title': 'సేవలు త్వరలో ప్రారంభమవుతాయి',
      'coming_soon_sub': 'పృథ్వీ ఫిక్స్ ప్రస్తుతం ఖోర్దా, కటక్ మరియు పూరీలలో అందుబాటులో ఉంది. మీ ప్రాంతంలో త్వరలో ప్రారంభం కానుంది.',
      'browse_bhubaneswar': 'భువనేశ్వర్ హబ్ చూడండి',
      'search_services_hint': 'ఎలక్ట్రీషియన్, ప్లంబర్, కార్పెంటర్ శోధించండి...',
      'trust_zero_brokerage': '₹0 దళారీ రుసుము',
      'trust_zero_brokerage_desc': 'నేరుగా సహకార బుకింగ్',
      'trust_93_worker': '93% కార్మికుడికి',
      'trust_93_worker_desc': 'న్యాయమైన వేతన నమూనా',
      'trust_police_verified': '100% ధృవీకృతం',
      'trust_police_verified_desc': 'ఆధార్ & పోలీస్ పరిశీలన',
      'trust_45min_sla': '45 నిమిషాల ప్రతిస్పందన',
      'trust_45min_sla_desc': 'ఆన్-డ్యూటీ దళం',
      'rate_calc_title': '93-2-5 పారదర్శక ధరల కాలిక్యులేటర్',
      'rate_calc_desc': 'కార్మికుడి వేతనం మరియు సహకార విభజనను స్లైడర్ ద్వారా తెలుసుకోండి.',
      'popular_trades': 'ధృవీకరించిన సహకార సేవలు',
      'view_all_trades': 'అన్ని సేవలను చూడండి',
      'authentic_reviews': 'పౌరుల సమీక్షలు',
      'authentic_reviews_sub': 'ఒడిశా పౌరుల నిజమైన అభిప్రాయాలు',
    },
  };
}

extension LocalizationExt on BuildContext {
  String tr(String key) => watch<LanguageProvider>().translate(key);
  String trRead(String key) => read<LanguageProvider>().translate(key);
}
